/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formulariop;

import CosmediaSpa.Formularios.CosmediaSpaFrm;
import conexion.conexion_mysql;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
/**
public class NewJFrame extends javax.swing.JFrame {
 *
 * @author vicom
 */
public class CosmediaSpaInicio extends javax.swing.JFrame {

    conexion_mysql con = new conexion_mysql();
    Connection cn = con.conectar();
    /**
     * Creates new form NewJFrame
     */
    public CosmediaSpaInicio() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_registrarse = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        txt_usuario = new javax.swing.JTextField();
        Txt_contrasena = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contraseña:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, -1, -1));

        btn_registrarse.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_registrarse.setForeground(new java.awt.Color(0, 0, 0));
        btn_registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        btn_registrarse.setText("Registrarse");
        btn_registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarseActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 740, 160, 40));

        btn_agregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_agregar.setForeground(new java.awt.Color(0, 0, 0));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sign-in.png"))); // NOI18N
        btn_agregar.setText("Entrar");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, 110, 40));

        txt_usuario.setForeground(new java.awt.Color(255, 255, 255));
        txt_usuario.setText("Ingrese su usuario");
        txt_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txt_usuarioMousePressed(evt);
            }
        });
        jPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 280, 60));

        Txt_contrasena.setForeground(new java.awt.Color(255, 255, 255));
        Txt_contrasena.setText("**********");
        Txt_contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Txt_contrasenaMousePressed(evt);
            }
        });
        jPanel1.add(Txt_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 630, 280, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagenvale.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1530, 820));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        //Instanciar
        String usuario = txt_usuario.getText().trim();
        String pass = new String(Txt_contrasena.getPassword()).trim();
        // Verificar si los campos están vacíos
        if (usuario.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(null, "DEBE COMPLETAR LOS DATOS");
            return;//Detener la ejecucion si los campos estan vacios
        }

        try {
            // Consulta SQL con parámetros
            String query = "SELECT nombre FROM users WHERE usuario = ? AND contraseña = ?";
            PreparedStatement ps = cn.prepareStatement(query);
            ps.setString(1, usuario);  // Parametrizamos el usuario
            ps.setString(2, pass);     // Parametrizamos la contraseña

            // Ejecutamos la consulta
            //ResultSet
            var rs = ps.executeQuery();
            // Verificamos si la consulta devuelve algún resultado
            if (rs.next()) {
                // Si los datos son correctos, cerrar la ventana de inicio de sesión
                dispose();
                CosmediaSpaFrm pg = new CosmediaSpaFrm();
                pg.setVisible(true); // Mostrar la ventana del panel de usuario

            } else {
                // Si el usuario o la contraseña son incorrectos
                JOptionPane.showMessageDialog(null, "USUARIO O CONTRASEÑA INCORRECTA");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR AL INICIAR SESION");
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarseActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here: 
        Registro newframe = new Registro ();
        newframe.setVisible(true);

        this.dispose();
        newframe.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btn_registrarseActionPerformed

    private void txt_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usuarioMousePressed
        // TODO add your handling code here:
         if (txt_usuario.getText().equals("Ingrese su usuario")) {
            txt_usuario.setText("");
            txt_usuario.setForeground(Color.gray);
        }
        if (String.valueOf(Txt_contrasena.getPassword()).isEmpty()) {
            Txt_contrasena.setText("**********");
            
            Txt_contrasena.setForeground(Color.gray);
        }
    }//GEN-LAST:event_txt_usuarioMousePressed

    private void Txt_contrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Txt_contrasenaMousePressed
        // TODO add your handling code here:
        
         if (String.valueOf(Txt_contrasena.getPassword()).equals("**********")) {
            Txt_contrasena.setText("");
            Txt_contrasena.setForeground(Color.gray);
        }
        if (txt_usuario.getText().isEmpty()) {
            txt_usuario.setText("Ingrese su usuario");
            txt_usuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_Txt_contrasenaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CosmediaSpaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CosmediaSpaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CosmediaSpaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CosmediaSpaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CosmediaSpaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Txt_contrasena;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_registrarse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
