/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package CosmediaSpa.Formularios;

/**
 *
 * @author vicom
 */
public class CosmediaSpaFrm extends javax.swing.JFrame {

    /**
     * Creates new form CosmediaSpaFrm
     */
    public CosmediaSpaFrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        helpMenu = new javax.swing.JMenu();
        frm_agenda = new javax.swing.JMenuItem();
        frm_clientes = new javax.swing.JMenu();
        frm_cliente = new javax.swing.JMenuItem();
        frm_consulta = new javax.swing.JMenu();
        frm_consultas = new javax.swing.JMenuItem();
        frm_tratamiento = new javax.swing.JMenu();
        frm_tratamientos = new javax.swing.JMenuItem();
        frm_empleado = new javax.swing.JMenu();
        frm_empleados = new javax.swing.JMenuItem();
        frm_detallefactura = new javax.swing.JMenu();
        frm_detallesfactura = new javax.swing.JMenuItem();
        frm_factura = new javax.swing.JMenu();
        frm_facturas = new javax.swing.JMenuItem();
        frm_pagos = new javax.swing.JMenu();
        frm_pago = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        frm_proveedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imgvale 5.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1040));

        desktopPane.add(jPanel1);
        jPanel1.setBounds(0, 0, 1920, 1040);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Agenda");

        frm_agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar.png"))); // NOI18N
        frm_agenda.setMnemonic('c');
        frm_agenda.setText("Organizar Agenda");
        frm_agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_agendaActionPerformed(evt);
            }
        });
        helpMenu.add(frm_agenda);

        menuBar.add(helpMenu);

        frm_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        frm_clientes.setText("Clientes");
        frm_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_clientesActionPerformed(evt);
            }
        });

        frm_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        frm_cliente.setText("Crear Cliente");
        frm_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_clienteActionPerformed(evt);
            }
        });
        frm_clientes.add(frm_cliente);

        menuBar.add(frm_clientes);

        frm_consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stethoscope.png"))); // NOI18N
        frm_consulta.setText("Consulta");
        frm_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_consultaActionPerformed(evt);
            }
        });

        frm_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stethoscope.png"))); // NOI18N
        frm_consultas.setText("Crear Consulta");
        frm_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_consultasActionPerformed(evt);
            }
        });
        frm_consulta.add(frm_consultas);

        menuBar.add(frm_consulta);

        frm_tratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        frm_tratamiento.setText("Tratamiento");
        frm_tratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_tratamientoActionPerformed(evt);
            }
        });

        frm_tratamientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        frm_tratamientos.setText("Organizar Tratamiento");
        frm_tratamientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_tratamientosActionPerformed(evt);
            }
        });
        frm_tratamiento.add(frm_tratamientos);

        menuBar.add(frm_tratamiento);

        frm_empleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        frm_empleado.setText("Empleado");
        frm_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_empleadoActionPerformed(evt);
            }
        });

        frm_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        frm_empleados.setText("Empleado");
        frm_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_empleadosActionPerformed(evt);
            }
        });
        frm_empleado.add(frm_empleados);

        menuBar.add(frm_empleado);

        frm_detallefactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png"))); // NOI18N
        frm_detallefactura.setText("Detalle Factura");
        frm_detallefactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_detallefacturaActionPerformed(evt);
            }
        });

        frm_detallesfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png"))); // NOI18N
        frm_detallesfactura.setText("Detalles de la Factura");
        frm_detallesfactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_detallesfacturaActionPerformed(evt);
            }
        });
        frm_detallefactura.add(frm_detallesfactura);

        menuBar.add(frm_detallefactura);

        frm_factura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png"))); // NOI18N
        frm_factura.setText("Factura");
        frm_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_facturaActionPerformed(evt);
            }
        });

        frm_facturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invoice.png"))); // NOI18N
        frm_facturas.setText("Crear Factura");
        frm_facturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_facturasActionPerformed(evt);
            }
        });
        frm_factura.add(frm_facturas);

        menuBar.add(frm_factura);

        frm_pagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/currency-dollar.png"))); // NOI18N
        frm_pagos.setText("Pagos");
        frm_pagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_pagosActionPerformed(evt);
            }
        });

        frm_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/currency-dollar.png"))); // NOI18N
        frm_pago.setText("Ordenar Pagos");
        frm_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_pagoActionPerformed(evt);
            }
        });
        frm_pagos.add(frm_pago);

        menuBar.add(frm_pagos);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/archive.png"))); // NOI18N
        jMenu1.setText("Proveedor");

        frm_proveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/archive.png"))); // NOI18N
        frm_proveedor.setText("Agregar Proveedores");
        frm_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frm_proveedorActionPerformed(evt);
            }
        });
        jMenu1.add(frm_proveedor);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frm_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_clienteActionPerformed
        frm_cliente objeto = new frm_cliente();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_clienteActionPerformed

    private void frm_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_clientesActionPerformed

    }//GEN-LAST:event_frm_clientesActionPerformed

    private void frm_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_consultasActionPerformed
        frm_consulta objeto = new frm_consulta();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_consultasActionPerformed

    private void frm_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_consultaActionPerformed

    }//GEN-LAST:event_frm_consultaActionPerformed

    private void frm_tratamientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_tratamientosActionPerformed
        frm_tratamiento objeto = new frm_tratamiento();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_tratamientosActionPerformed

    private void frm_tratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_tratamientoActionPerformed

    }//GEN-LAST:event_frm_tratamientoActionPerformed

    private void frm_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_empleadosActionPerformed
        frm_empleado objeto = new frm_empleado();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_empleadosActionPerformed

    private void frm_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_empleadoActionPerformed

    }//GEN-LAST:event_frm_empleadoActionPerformed

    private void frm_detallesfacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_detallesfacturaActionPerformed
        frm_detallefactura objeto = new frm_detallefactura();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_detallesfacturaActionPerformed

    private void frm_detallefacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_detallefacturaActionPerformed

    }//GEN-LAST:event_frm_detallefacturaActionPerformed

    private void frm_facturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_facturasActionPerformed
        frm_factura objeto = new frm_factura();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_facturasActionPerformed

    private void frm_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_facturaActionPerformed

    }//GEN-LAST:event_frm_facturaActionPerformed

    private void frm_pagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_pagosActionPerformed
        frm_pago objeto = new frm_pago();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_pagosActionPerformed

    private void frm_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_proveedorActionPerformed
        frm_proveedor objeto = new frm_proveedor();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_proveedorActionPerformed

    private void frm_agendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_agendaActionPerformed
        frm_agenda objeto = new frm_agenda();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_agendaActionPerformed

    private void frm_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frm_pagoActionPerformed
        frm_pago objeto = new frm_pago();
        desktopPane.add(objeto);
        objeto.setVisible(true);
    }//GEN-LAST:event_frm_pagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CosmediaSpaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CosmediaSpaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CosmediaSpaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CosmediaSpaFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CosmediaSpaFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem frm_agenda;
    private javax.swing.JMenuItem frm_cliente;
    private javax.swing.JMenu frm_clientes;
    private javax.swing.JMenu frm_consulta;
    private javax.swing.JMenuItem frm_consultas;
    private javax.swing.JMenu frm_detallefactura;
    private javax.swing.JMenuItem frm_detallesfactura;
    private javax.swing.JMenu frm_empleado;
    private javax.swing.JMenuItem frm_empleados;
    private javax.swing.JMenu frm_factura;
    private javax.swing.JMenuItem frm_facturas;
    private javax.swing.JMenuItem frm_pago;
    private javax.swing.JMenu frm_pagos;
    private javax.swing.JMenuItem frm_proveedor;
    private javax.swing.JMenu frm_tratamiento;
    private javax.swing.JMenuItem frm_tratamientos;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
