/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CosmediaSpa.Formularios;

import CosmediaSpa.Consulta;
import CosmediaSpa.Validacion;
import java.io.File;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vicom
 */
public class frm_consulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_consulta
     */
    private DefaultTableModel modeloTabla;
    private boolean editMode = false;
    private int editRow = -1;

    public frm_consulta() {
        initComponents();
        inicializarTabla();
    }

    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[]{"Código", "Motivo", "Duración", "Precio"}, 0
        );
        tabla_consulta.setModel(modeloTabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_duracionminutos = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_consulta = new javax.swing.JTable();
        txt_codigo = new javax.swing.JTextField();
        txt_motivo = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consulta");

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo");

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        jLabel2.setText("Motivo:");

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Duracion (Minutos):");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio:");

        tabla_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_consulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_precio, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(txt_duracionminutos)
                                    .addComponent(txt_motivo)
                                    .addComponent(txt_codigo)))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_agregar)
                        .addGap(28, 28, 28)
                        .addComponent(btn_editar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)
                        .addGap(73, 73, 73)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_duracionminutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_editar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_buscar))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (editMode) {
        JOptionPane.showMessageDialog(this, "Está en modo edición. Termine antes de agregar.");
        return;
    }
    if (!validarCampos()) return;

    String codigo = txt_codigo.getText().trim();
    String motivo = txt_motivo.getText().trim();
    int duracion;
    double precio;

    try {
        duracion = Integer.parseInt(txt_duracionminutos.getText().trim());
        if (duracion < 0) throw new NumberFormatException();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "La duración debe ser un entero no negativo.");
        return;
    }

    try {
        precio = Double.parseDouble(txt_precio.getText().trim());
        if (precio < 0) throw new NumberFormatException();
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "El precio debe ser un número no negativo.");
        return;
    }

    // Crear la consulta
    Consulta c = new Consulta(codigo, motivo, precio, duracion);

    // Establecer archivo fijo automáticamente
    c.setArchivo(new File("consulta_" + codigo + ".txt"));

    // Guardar en disco
    if (!c.mtd_guardar()) {
        JOptionPane.showMessageDialog(this, "Error al guardar el archivo de consulta.");
        return;
    }

    // Evitar duplicados
    if (Consulta.existeRegistro(modeloTabla, codigo)) {
        JOptionPane.showMessageDialog(this, "Ya existe esa consulta en la tabla.");
        return;
    }

    // Añadir a tabla
    modeloTabla.addRow(new Object[]{codigo, motivo, duracion, precio});
    limpiarCampos();
    JOptionPane.showMessageDialog(this, "Consulta guardada correctamente.");
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
      if (!editMode) {
        int fila = tabla_consulta.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para editar.");
            return;
        }
        // Cargar en campos
        txt_codigo.setText(modeloTabla.getValueAt(fila, 0).toString());
        txt_motivo.setText(modeloTabla.getValueAt(fila, 1).toString());
        txt_duracionminutos.setText(modeloTabla.getValueAt(fila, 2).toString());
        txt_precio.setText(modeloTabla.getValueAt(fila, 3).toString());

        editMode = true;
        editRow = fila;
        btn_editar.setText("GUARDAR");
        btn_agregar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_buscar.setEnabled(false);
    } else {
        // Guardar cambios
        if (!validarCampos()) return;

        String codigo = txt_codigo.getText().trim();
        String motivo = txt_motivo.getText().trim();
        int duracion = Integer.parseInt(txt_duracionminutos.getText().trim());
        double precio = Double.parseDouble(txt_precio.getText().trim());

        Consulta c = new Consulta(codigo, motivo, precio, duracion);
        if (!c.mtd_guardar()) {
            JOptionPane.showMessageDialog(this, "Error al actualizar el archivo de consulta.");
            return;
        }

        modeloTabla.setValueAt(codigo, editRow, 0);
        modeloTabla.setValueAt(motivo, editRow, 1);
        modeloTabla.setValueAt(duracion, editRow, 2);
        modeloTabla.setValueAt(precio, editRow, 3);

        // Salir de edición
        editMode = false;
        editRow = -1;
        btn_editar.setText("EDITAR");
        btn_agregar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_buscar.setEnabled(true);

        limpiarCampos();
        JOptionPane.showMessageDialog(this, "Consulta actualizada correctamente.");
    }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
      if (editMode) {
        JOptionPane.showMessageDialog(this, "No puede eliminar mientras edita.");
        return;
    }
    int fila = tabla_consulta.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.");
        return;
    }
    String codigo = modeloTabla.getValueAt(fila, 0).toString();
    Consulta c = new Consulta();
    c.setCodigo(codigo);
    if (!c.mtd_eliminar()) {
        JOptionPane.showMessageDialog(this, "No se pudo eliminar el archivo de consulta.");
        return;
    }
    modeloTabla.removeRow(fila);
    limpiarCampos();
    JOptionPane.showMessageDialog(this, "Consulta eliminada correctamente.");
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       if (editMode) {
        JOptionPane.showMessageDialog(this, "No puede buscar mientras edita.");
        return;
    }
    Consulta c = new Consulta();
    if (!c.mtd_buscar()) {
        JOptionPane.showMessageDialog(this, "No se cargó ninguna consulta o se canceló.");
        return;
    }
    String codigo = c.getCodigo();
    String motivo = c.getMotivo();
    int duracion = c.getDuracionMinutos();
    double precio = c.getPrecio();

    txt_codigo.setText(codigo);
    txt_motivo.setText(motivo);
    txt_duracionminutos.setText(String.valueOf(duracion));
    txt_precio.setText(new DecimalFormat("0.##").format(precio));

    // Evitar duplicados y seleccionar fila
    if (!Consulta.existeRegistro(modeloTabla, codigo)) {
        modeloTabla.addRow(new Object[]{codigo, motivo, duracion, precio});
    }
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        if (modeloTabla.getValueAt(i, 0).equals(codigo)) {
            tabla_consulta.setRowSelectionInterval(i, i);
            break;
        }
    }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void limpiarCampos() {
        txt_codigo.setText("");
        txt_motivo.setText("");
        txt_duracionminutos.setText("");
        txt_precio.setText("");
        tabla_consulta.clearSelection();
    }

    private boolean validarCampos() {
        String codigo = txt_codigo.getText().trim();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El código no puede estar vacío.");
            return false;
        }
        String motivo = txt_motivo.getText().trim();
        if (motivo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El motivo no puede estar vacío.");
            return false;
        }
        String dur = txt_duracionminutos.getText().trim();
        if (dur.isEmpty() || !Validacion.esSoloDigitos(dur)) {
            JOptionPane.showMessageDialog(this, "La duración debe ser un número entero.");
            return false;
        }
        String pr = txt_precio.getText().trim();
        try {
            double precio = Double.parseDouble(pr);
            if (precio < 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número no negativo.");
            return false;
        }
        return true;
    }
    
    public static boolean existeRegistro(javax.swing.table.DefaultTableModel model, String cedula) {
    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 0).equals(cedula)) {
            return true;
        }
    }
    return false;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_consulta;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_duracionminutos;
    private javax.swing.JTextField txt_motivo;
    private javax.swing.JTextField txt_precio;
    // End of variables declaration//GEN-END:variables
}
