/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CosmediaSpa.Formularios;

import CosmediaSpa.Agenda;
import CosmediaSpa.Validacion;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vicom
 */
public class frm_agenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form frm_agenda
     */
    private DefaultTableModel modeloTabla;
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private boolean editMode = false;
    private int editRow = -1;

    public frm_agenda() {
        initComponents();
        inicializarTabla();
    }

    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[]{"Código", "CédulaCliente", "CódigoServicio", "FechaCita", "Cantidad"}, 0
        );
        tabla_agenda.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_codigos = new javax.swing.JTextField();
        txt_cedulasclientes = new javax.swing.JTextField();
        txt_codigosservicios = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        cb_fechacita = new org.jdesktop.swingx.JXDatePicker();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_agenda = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agenda");

        jLabel1.setText("Codigos:");

        jLabel2.setText("Cedulas Clientes:");

        jLabel3.setText("Codigos Servicios:");

        jLabel4.setText("Fecha de la Cita:");

        jLabel5.setText("Cantidad:");

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tabla_agenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_agenda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btn_agregar)
                        .addGap(28, 28, 28)
                        .addComponent(btn_editar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigos)
                            .addComponent(txt_cedulasclientes)
                            .addComponent(txt_codigosservicios)
                            .addComponent(txt_cantidad)
                            .addComponent(cb_fechacita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_codigos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_cedulasclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_codigosservicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cb_fechacita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar)
                            .addComponent(btn_editar)
                            .addComponent(btn_eliminar)
                            .addComponent(btn_buscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (editMode) {
            JOptionPane.showMessageDialog(this,
                    "Está en modo edición. Termine antes de agregar.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCampos()) {
            return;
        }

        String codigo = txt_codigos.getText().trim();
        String cedulaCliente = txt_cedulasclientes.getText().trim();
        String codigoServicio = txt_codigosservicios.getText().trim();
        Date fechaCita = cb_fechacita.getDate();
        int cantidad;
        try {
            cantidad = Integer.parseInt(txt_cantidad.getText().trim());
            if (cantidad < 1) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "La cantidad debe ser un entero mayor que cero.",
                    "Error de validación",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Agenda ag = new Agenda(codigo, cedulaCliente, codigoServicio, fechaCita, cantidad);

        // 1) Comprobar duplicado en disco
        if (ag.existeRegistro()) {
            JOptionPane.showMessageDialog(this,
                    "Ya existe una cita con ese código.",
                    "Duplicado",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2) Guardar en .txt
        if (!ag.mtd_guardar()) {
            JOptionPane.showMessageDialog(this,
                    "Error al guardar la cita en archivo.",
                    "Error I/O",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3) Añadir a la tabla
        modeloTabla.addRow(new Object[]{
            codigo,
            cedulaCliente,
            codigoServicio,
            sdf.format(fechaCita),
            cantidad
        });

        limpiarCampos();
        JOptionPane.showMessageDialog(this,
                "Cita guardada correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (!editMode) {
            int fila = tabla_agenda.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(this,
                        "Seleccione una fila para editar.",
                        "Atención",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            // cargar fila a campos
            txt_codigos.setText(modeloTabla.getValueAt(fila, 0).toString());
            txt_cedulasclientes.setText(modeloTabla.getValueAt(fila, 1).toString());
            txt_codigosservicios.setText(modeloTabla.getValueAt(fila, 2).toString());
            try {
                Date d = sdf.parse(modeloTabla.getValueAt(fila, 3).toString());
                cb_fechacita.setDate(d);
            } catch (Exception e) {
                cb_fechacita.setDate(new Date());
            }
            txt_cantidad.setText(modeloTabla.getValueAt(fila, 4).toString());

            editMode = true;
            editRow = fila;
            btn_editar.setText("GUARDAR");
        } else {
            // guardar cambios
            if (!validarCampos()) {
                return;
            }

            String codigo = txt_codigos.getText().trim();
            String cedulaCliente = txt_cedulasclientes.getText().trim();
            String codigoServicio = txt_codigosservicios.getText().trim();
            Date fechaCita = cb_fechacita.getDate();
            int cantidad;
            try {
                cantidad = Integer.parseInt(txt_cantidad.getText().trim());
                if (cantidad < 1) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this,
                        "La cantidad debe ser un entero mayor que cero.",
                        "Error de validación",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            Agenda ag = new Agenda(codigo, cedulaCliente, codigoServicio, fechaCita, cantidad);
            // no comprobamos existeRegistro() porque queremos sobrescribir
            if (!ag.mtd_guardar()) {
                JOptionPane.showMessageDialog(this,
                        "Error al actualizar la cita en archivo.",
                        "Error I/O",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // actualizar tabla
            modeloTabla.setValueAt(codigo, editRow, 0);
            modeloTabla.setValueAt(cedulaCliente, editRow, 1);
            modeloTabla.setValueAt(codigoServicio, editRow, 2);
            modeloTabla.setValueAt(sdf.format(fechaCita), editRow, 3);
            modeloTabla.setValueAt(cantidad, editRow, 4);

            limpiarCampos();
            editMode = false;
            btn_editar.setText("EDITAR");
            JOptionPane.showMessageDialog(this,
                    "Cita actualizada correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (editMode) {
            JOptionPane.showMessageDialog(this,
                    "No puede eliminar mientras edita. Primero guarde o cancele.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = tabla_agenda.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una fila para eliminar.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String codigo = modeloTabla.getValueAt(fila, 0).toString();
        Agenda ag = new Agenda();
        ag.setCodigo(codigo);
        if (!ag.mtd_eliminar()) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el archivo de la cita.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        modeloTabla.removeRow(fila);
        limpiarCampos();
        JOptionPane.showMessageDialog(this,
                "Cita eliminada correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if (editMode) {
            JOptionPane.showMessageDialog(this,
                    "No puede buscar mientras edita. Termine edición primero.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        limpiarCampos();

        Agenda ag = new Agenda();
        if (!ag.mtd_buscar()) {
            JOptionPane.showMessageDialog(this,
                    "No se cargó ninguna cita o se canceló.",
                    "Información",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String codigo = ag.getCodigo();
        String cedulaCliente = ag.getCedulaCliente();
        String codigoServicio = ag.getCodigoServicio();
        Date fechaCita = ag.getFechaCita();
        int cantidad = ag.getCantidad();

        txt_codigos.setText(codigo);
        txt_cedulasclientes.setText(cedulaCliente);
        txt_codigosservicios.setText(codigoServicio);
        cb_fechacita.setDate(fechaCita);
        txt_cantidad.setText(String.valueOf(cantidad));

        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            if (modeloTabla.getValueAt(i, 0).equals(codigo)) {
                tabla_agenda.setRowSelectionInterval(i, i);
                editRow = i;
                editMode = true;
                btn_editar.setText("GUARDAR");
                return;
            }
        }
        modeloTabla.addRow(new Object[]{
            codigo,
            cedulaCliente,
            codigoServicio,
            sdf.format(fechaCita),
            cantidad
        });
        int nuevaFila = modeloTabla.getRowCount() - 1;
        tabla_agenda.setRowSelectionInterval(nuevaFila, nuevaFila);
        editRow = nuevaFila;
        editMode = true;
        btn_editar.setText("GUARDAR");
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void limpiarCampos() {
        txt_codigos.setText("");
        txt_cedulasclientes.setText("");
        txt_codigosservicios.setText("");
        cb_fechacita.setDate(new Date());
        txt_cantidad.setText("");
        tabla_agenda.clearSelection();
    }

    private boolean validarCampos() {
        String codigo = txt_codigos.getText().trim();
        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El código no puede estar vacío.");
            return false;
        }

        String cedula = txt_cedulasclientes.getText().trim();
        // Llamamos al método estático validarCedula en lugar de intentar instanciar Validacion
        if (cedula.isEmpty() || !Validacion.validarCedula(cedula)) {
            JOptionPane.showMessageDialog(this, "Ingrese una cédula válida.");
            return false;
        }

        String servicio = txt_codigosservicios.getText().trim();
        if (servicio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El código de servicio no puede estar vacío.");
            return false;
        }

        Date f = cb_fechacita.getDate();
        if (f == null) {
            JOptionPane.showMessageDialog(this, "Seleccione una fecha de cita.");
            return false;
        }

        if (txt_cantidad.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La cantidad no puede estar vacía.");
            return false;
        }

        // Aquí podrías validar que txt_cantidad sea un número entero, etc.
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private org.jdesktop.swingx.JXDatePicker cb_fechacita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_agenda;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cedulasclientes;
    private javax.swing.JTextField txt_codigos;
    private javax.swing.JTextField txt_codigosservicios;
    // End of variables declaration//GEN-END:variables
}
