/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CosmediaSpa.Formularios;

/**
 *
 * @author vicom
 */
import CosmediaSpa.Tratamiento;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frm_tratamiento extends javax.swing.JInternalFrame {

    
  private DefaultTableModel modeloTabla;
    private boolean editMode = false;
    private int editRow = -1;

    public frm_tratamiento() {
        initComponents();
        inicializarTabla();
    }
    
    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[]{"Código","Descripción","Cantidad","Precio Unit.","Total"}, 0
        );
        tabla_tratamiento.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_eliminar = new javax.swing.JButton();
        txt_precio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_tratamiento = new javax.swing.JTable();
        txt_total = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        txt_codigoservicio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_cantidadsesiones = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Tratamiento");

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad Sesiones:");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio Unitario:");

        tabla_tratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_tratamiento);

        jLabel5.setText("Total:");

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo de Servicio:");

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane2.setViewportView(txt_descripcion);

        jLabel2.setText("Descripcion Servicio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigoservicio)
                            .addComponent(txt_cantidadsesiones)
                            .addComponent(txt_precio)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(txt_total))
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_agregar)
                        .addGap(28, 28, 28)
                        .addComponent(btn_editar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_codigoservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cantidadsesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar)
                            .addComponent(btn_editar)
                            .addComponent(btn_eliminar)
                            .addComponent(btn_buscar))))
                .addGap(158, 158, 158))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       if (editMode) {
            JOptionPane.showMessageDialog(this,
                "No puedes eliminar mientras editas.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = tabla_tratamiento.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                "Selecciona una fila para eliminar.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String codigo = modeloTabla.getValueAt(fila, 0).toString();
        Tratamiento t = new Tratamiento();
        t.setCodigoServicio(codigo);
        if (!t.mtd_eliminar()) {
            JOptionPane.showMessageDialog(this,
                "No se pudo eliminar el archivo.",
                "Error I/O", JOptionPane.ERROR_MESSAGE);
            return;
        }
        modeloTabla.removeRow(fila);
        limpiarCampos();
        JOptionPane.showMessageDialog(this,
            "Tratamiento eliminado de archivo y tabla.",
            "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       if (editMode) {
            JOptionPane.showMessageDialog(this,
                "No puedes buscar mientras editas.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        limpiarCampos();
        Tratamiento t = new Tratamiento();
        if (!t.mtd_buscar()) return;

        txt_codigoservicio.setText(t.getCodigoServicio());
        txt_descripcion.setText(t.getDescripcionServicio());
        txt_cantidadsesiones.setText(String.valueOf(t.getCantidadSesiones()));
        txt_precio.setText(String.valueOf(t.getPrecioUnitario()));
        txt_total.setText(String.valueOf(t.getTotalLinea()));

        String codigo = t.getCodigoServicio();
        if (!existeRegistro(modeloTabla, codigo)) {
            modeloTabla.addRow(new Object[]{
                codigo,
                t.getDescripcionServicio(),
                t.getCantidadSesiones(),
                t.getPrecioUnitario(),
                t.getTotalLinea()
            });
        }
        int f = modeloTabla.getRowCount() - 1;
        tabla_tratamiento.setRowSelectionInterval(f, f);

        editMode = true;
        editRow = f;
        btn_editar.setText("GUARDAR");
        btn_agregar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (editMode) {
            JOptionPane.showMessageDialog(this,
                "Termina la edición antes de agregar otro.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCampos()) return;

        String codigo = txt_codigoservicio.getText().trim();
        String descripcion = txt_descripcion.getText().trim();
        int cantidad;
        double precio;
        try {
            cantidad = Integer.parseInt(txt_cantidadsesiones.getText().trim());
            if (cantidad < 1) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Cantidad de sesiones inválida.",
                "Error de validación", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            precio = Double.parseDouble(txt_precio.getText().trim());
            if (precio < 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Precio unitario inválido.",
                "Error de validación", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Tratamiento t = new Tratamiento(codigo, descripcion, cantidad, precio);
        if (!t.mtd_guardar()) {
            JOptionPane.showMessageDialog(this,
                "Error al guardar tratamiento en archivo.",
                "Error I/O", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (existeRegistro(modeloTabla, codigo)) {
            JOptionPane.showMessageDialog(this,
                "Ya existe ese tratamiento en la tabla.",
                "Duplicado", JOptionPane.WARNING_MESSAGE);
            limpiarCampos();
            return;
        }

        double totalLinea = cantidad * precio;
        modeloTabla.addRow(new Object[]{codigo, descripcion, cantidad, precio, totalLinea});
        JOptionPane.showMessageDialog(this,
            "Tratamiento guardado en archivo y tabla.",
            "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (!editMode) {

            int fila = tabla_tratamiento.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(this,
                    "Selecciona una fila para editar.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }

            txt_codigoservicio.setText(modeloTabla.getValueAt(fila, 0).toString());
            txt_descripcion.setText(modeloTabla.getValueAt(fila, 1).toString());
            txt_cantidadsesiones.setText(modeloTabla.getValueAt(fila, 2).toString());
            txt_precio.setText(modeloTabla.getValueAt(fila, 3).toString());
            txt_total.setText(modeloTabla.getValueAt(fila, 4).toString());

            editMode = true;
            editRow = fila;
            btn_editar.setText("GUARDAR");
            btn_agregar.setEnabled(false);
            btn_eliminar.setEnabled(false);
        } else {

            if (!validarCampos()) return;

            String codigo = txt_codigoservicio.getText().trim();
            String descripcion = txt_descripcion.getText().trim();
            int cantidad = Integer.parseInt(txt_cantidadsesiones.getText().trim());
            double precio = Double.parseDouble(txt_precio.getText().trim());

            Tratamiento t = new Tratamiento(codigo, descripcion, cantidad, precio);
            if (!t.mtd_guardar()) {
                JOptionPane.showMessageDialog(this,
                    "Error al actualizar tratamiento.",
                    "Error I/O", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double totalLinea = cantidad * precio;

            modeloTabla.setValueAt(codigo, editRow, 0);
            modeloTabla.setValueAt(descripcion, editRow, 1);
            modeloTabla.setValueAt(cantidad, editRow, 2);
            modeloTabla.setValueAt(precio, editRow, 3);
            modeloTabla.setValueAt(totalLinea, editRow, 4);

            JOptionPane.showMessageDialog(this,
                "Tratamiento actualizado.",
                "Éxito", JOptionPane.INFORMATION_MESSAGE);

            editMode = false;
            editRow = -1;
            btn_editar.setText("EDITAR");
            btn_agregar.setEnabled(true);
            btn_eliminar.setEnabled(true);
            limpiarCampos();
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private boolean validarCampos() {
        if (txt_codigoservicio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Código vacío.",
                "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txt_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Descripción vacía.",
                "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            int c = Integer.parseInt(txt_cantidadsesiones.getText().trim());
            if (c < 1) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.",
                "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            double p = Double.parseDouble(txt_precio.getText().trim());
            if (p < 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Precio inválido.",
                "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }

        int cantidad = Integer.parseInt(txt_cantidadsesiones.getText().trim());
        double precio = Double.parseDouble(txt_precio.getText().trim());
        txt_total.setText(String.valueOf(cantidad * precio));
        return true;
    }

    private void limpiarCampos() {
        txt_codigoservicio.setText("");
        txt_descripcion.setText("");
        txt_cantidadsesiones.setText("");
        txt_precio.setText("");
        txt_total.setText("");
        tabla_tratamiento.clearSelection();
    }

    private static boolean existeRegistro(DefaultTableModel model, String clave) {
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(clave)) {
                return true;
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_tratamiento;
    private javax.swing.JTextField txt_cantidadsesiones;
    private javax.swing.JTextField txt_codigoservicio;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
