/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CosmediaSpa.Formularios;

import CosmediaSpa.Cliente;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author vicom
 */
public class frm_cliente extends javax.swing.JInternalFrame {

    // Modelo de la tabla
    private DefaultTableModel modeloTabla;
    // Formateador de fecha
    private final SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    // Control de modo edición
    private boolean editMode = false;
    private int editRow = -1;

    // --- Constructor ---
    public frm_cliente() {
        initComponents();
        inicializarTabla();
        limpiarCampos();
    }

    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
                new Object[]{"Cédula", "Nombre", "Dirección", "Teléfono", "Email", "FechaReg"}, 0
        );
        tabla_clientes.setModel(modeloTabla);
    }

    private void limpiarCampos() {
        txt_cedula.setText("");
        txt_nombre.setText("");
        txt_direccion.setText("");
        txt_telefono.setText("");
        txt_email.setText("");
        cb_fechaderegistro.setDate(new Date());
        editMode = false;
        editRow = -1;
        btn_editar.setText("EDITAR");
    }

    private boolean validarCampos() {
        String cedula = txt_cedula.getText().trim();
        String nombre = txt_nombre.getText().trim();
        String direccion = txt_direccion.getText().trim();
        String telefono = txt_telefono.getText().trim();
        String email = txt_email.getText().trim();
        Date fechaReg = cb_fechaderegistro.getDate();

        Cliente cli = new Cliente(cedula, nombre, direccion, telefono, email, fechaReg);
        if (!cli.validarDatos()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor ingrese datos válidos en todos los campos (cédula, email y teléfono).",
                    "Error de validación", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        cb_fechaderegistro = new org.jdesktop.swingx.JXDatePicker();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_clientes = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cliente");

        jLabel1.setText("Cedula:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Direccion:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("E-mail:");

        jLabel6.setText("Fecha de Registro:");

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tabla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_clientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cb_fechaderegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btn_agregar)
                        .addGap(28, 28, 28)
                        .addComponent(btn_editar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cb_fechaderegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar)
                            .addComponent(btn_editar)
                            .addComponent(btn_eliminar)
                            .addComponent(btn_buscar))
                        .addGap(49, 49, 49)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
      if (!validarCampos()) return;

    String cedula    = txt_cedula.getText().trim();
    String nombre    = txt_nombre.getText().trim();
    String direccion = txt_direccion.getText().trim();
    String telefono  = txt_telefono.getText().trim();
    String email     = txt_email.getText().trim();
    Date   fecha     = cb_fechaderegistro.getDate();

    Cliente cli = new Cliente(cedula, nombre, direccion, telefono, email, fecha);

    // 1) Creamos el JFileChooser y lo configuramos:
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Guardar Cliente (.txt)");
    chooser.setSelectedFile(new File("cliente_" + cedula + ".txt"));
    chooser.setFileFilter(
        new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt")
    );

    // 2) Lo inyectamos en el cliente:
    cli.setFileChooser(chooser);

    // 3) Llamamos a su mtd_guardar() (ya no pide parámetros):
    if (!cli.mtd_guardar()) {
        // canceló o error
        return;
    }

    // 4) Verificamos duplicados en la tabla:
    if (Cliente.existeRegistro(modeloTabla, cedula)) {
        JOptionPane.showMessageDialog(this,
            "Ya existe un cliente con esa cédula en la tabla.",
            "Duplicado", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 5) Insertamos la fila, usando TU sdf para la fecha:
    modeloTabla.addRow(new Object[]{
        cli.getCedula(),
        cli.getNombre(),
        cli.getDireccion(),
        cli.getTelefono(),
        cli.getEmail(),
        sdf.format(cli.getFechaRegistro())
    });

    JOptionPane.showMessageDialog(this,
        "Cliente guardado en archivo y tabla.",
        "Éxito", JOptionPane.INFORMATION_MESSAGE);
    limpiarCampos();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (!editMode) {
        // Entrar en modo edición
        int fila = tabla_clientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                "Seleccione una fila para editar.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Volcar valores a los campos
        txt_cedula.setText(modeloTabla.getValueAt(fila, 0).toString());
        txt_nombre.setText(modeloTabla.getValueAt(fila, 1).toString());
        txt_direccion.setText(modeloTabla.getValueAt(fila, 2).toString());
        txt_telefono.setText(modeloTabla.getValueAt(fila, 3).toString());
        txt_email.setText(modeloTabla.getValueAt(fila, 4).toString());
        try {
            Date fecha = sdf.parse(modeloTabla.getValueAt(fila, 5).toString());
            cb_fechaderegistro.setDate(fecha);
        } catch (ParseException ex) {
            cb_fechaderegistro.setDate(new Date());
        }
        // Activar modo edición
        editMode = true;
        editRow  = fila;
        btn_editar.setText("GUARDAR");
        btn_agregar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_buscar .setEnabled(false);
    } else {
        // --- Guardar cambios ---
        if (!validarCampos()) return;

        String cedula    = txt_cedula.getText().trim();
        String nombre    = txt_nombre.getText().trim();
        String direccion = txt_direccion.getText().trim();
        String telefono  = txt_telefono.getText().trim();
        String email     = txt_email.getText().trim();
        Date   fecha     = cb_fechaderegistro.getDate();

        // Recreamos el objeto Cliente con los nuevos datos
        Cliente cli = new Cliente(cedula, nombre, direccion, telefono, email, fecha);

        // Inyectamos un JFileChooser configurado para guardar
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Guardar Cliente (.txt)");
        chooser.setSelectedFile(new File("cliente_" + cedula + ".txt"));
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));
        cli.setFileChooser(chooser);

        // Llamamos al mtd_guardar() sin parámetros
        if (!cli.mtd_guardar()) {
            JOptionPane.showMessageDialog(this,
                "Error al actualizar archivo de cliente.",
                "Error I/O", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Actualizamos la fila en la tabla
        modeloTabla.setValueAt(cedula,   editRow, 0);
        modeloTabla.setValueAt(nombre,   editRow, 1);
        modeloTabla.setValueAt(direccion,editRow, 2);
        modeloTabla.setValueAt(telefono, editRow, 3);
        modeloTabla.setValueAt(email,    editRow, 4);
        modeloTabla.setValueAt(sdf.format(fecha), editRow, 5);

        JOptionPane.showMessageDialog(this,
            "Cliente actualizado en archivo y tabla.",
            "Éxito", JOptionPane.INFORMATION_MESSAGE);

        // Salimos de modo edición
        limpiarCampos();
    }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int fila = tabla_clientes.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Seleccione una fila de la tabla para eliminar.",
                    "Atención",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 1) Obtener la cédula de la fila seleccionada
        String cedula = modeloTabla.getValueAt(fila, 0).toString();

        // 2) Eliminar el archivo físico
        Cliente cli = new Cliente();
        cli.setCedula(cedula);
        boolean okArchivo = cli.mtd_eliminar();

        if (okArchivo) {
            // 3) Remover la fila de la tabla
            modeloTabla.removeRow(fila);

            // 4) Limpiar selección y campos del formulario
            tabla_clientes.clearSelection();
            txt_cedula.setText("");
            txt_nombre.setText("");
            txt_direccion.setText("");
            txt_telefono.setText("");
            txt_email.setText("");
            cb_fechaderegistro.setDate(new Date());

            JOptionPane.showMessageDialog(
                    this,
                    "Cliente eliminado de archivo y tabla.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo eliminar el cliente (archivo no encontrado).",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       if (editMode) {
            JOptionPane.showMessageDialog(this,
                "No puede buscar mientras edita.",
                "Atención",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Limpiar formulario
        limpiarCampos();

        // Abrir diálogo y cargar datos en el objeto
        Cliente cli = new Cliente();
        boolean ok = cli.mtd_buscar();
        if (!ok) {
            JOptionPane.showMessageDialog(this,
                "No se cargó ningún cliente o se canceló la selección.",
                "Información",
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String cedula    = cli.getCedula();
        txt_cedula.setText(cedula);
        txt_nombre.setText(cli.getNombre());
        txt_direccion.setText(cli.getDireccion());
        txt_telefono.setText(cli.getTelefono());
        txt_email.setText(cli.getEmail());
        cb_fechaderegistro.setDate(cli.getFechaRegistro());

        // ←←← Chequeo duplicado:
        if (Cliente.existeRegistro(modeloTabla, cedula)) {
            // sólo selecciono la fila existente
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                if (modeloTabla.getValueAt(i, 0).equals(cedula)) {
                    tabla_clientes.setRowSelectionInterval(i, i);
                    break;
                }
            }
            return;
        }

        // si no existía, la agrego
        modeloTabla.addRow(new Object[]{
            cedula,
            cli.getNombre(),
            cli.getDireccion(),
            cli.getTelefono(),
            cli.getEmail(),
            sdf.format(cli.getFechaRegistro())
        });
        int nuevaFila = modeloTabla.getRowCount() - 1;
        tabla_clientes.setRowSelectionInterval(nuevaFila, nuevaFila);
    }//GEN-LAST:event_btn_buscarActionPerformed

    public static boolean existeRegistro(javax.swing.table.DefaultTableModel model, String cedula) {
    for (int i = 0; i < model.getRowCount(); i++) {
        if (model.getValueAt(i, 0).equals(cedula)) {
            return true;
        }
    }
    return false;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private org.jdesktop.swingx.JXDatePicker cb_fechaderegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_clientes;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
