/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CosmediaSpa.Formularios;

import CosmediaSpa.Cliente;
import CosmediaSpa.Consulta;
import CosmediaSpa.Tratamiento;
import CosmediaSpa.DetalleFactura;
import CosmediaSpa.Factura;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author vicom
 */
public class frm_factura extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloCliente;
    private DefaultTableModel modeloConsulta;
    private DefaultTableModel modeloTratamiento;
    private DefaultTableModel modeloDetFactura;
    private DefaultTableModel modeloFactura;
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    private boolean editMode = false;
    private int editRow = -1;
    private boolean editModeFactura = false;
    private int editRowFactura = -1;

    public frm_factura() {
        initComponents();
        inicializarTablas();
        txt_subtotal.addActionListener(e -> actualizarMontos());
        cmb_descuento.addActionListener(e -> actualizarMontos());
        txt_cedula.setEditable(true);
        txt_nombre.setEditable(true);
        txt_numerofactura.setEditable(true);
        cb_fecha.getEditor().setEditable(true);
        cb_fecha.setEnabled(true);
        cmb_descuento.addActionListener(e -> recalcular());
        limpiarCamposDetFactura();
        limpiarCamposTratamiento();
        modeloConsulta = (DefaultTableModel) tabla_consulta.getModel();
        modeloTratamiento = (DefaultTableModel) tabla_tratamiento.getModel();

    }

    private void inicializarTablas() {
        modeloCliente = new DefaultTableModel(
                new Object[]{"Cédula", "Nombre", "Dirección", "Teléfono", "Email", "FechaReg"}, 0
        );
        tabla_cliente.setModel(modeloCliente);

        modeloConsulta = new DefaultTableModel(
                new Object[]{"Código", "Motivo", "Duración", "Precio"}, 0
        );
        tabla_consulta.setModel(modeloConsulta);

        modeloTratamiento = new DefaultTableModel(
                new String[]{"Código", "Descripción", "Cantidad", "PrecioUnit", "TotalLinea"}, 0
        );
        tabla_tratamiento.setModel(modeloTratamiento);

        modeloDetFactura = new DefaultTableModel(
                new String[]{"ProdID", "ProdNombre", "Cantidad", "Precio", "TotalLinea"}, 0
        );
        tabla_detallefactura.setModel(modeloDetFactura);

        modeloFactura = new DefaultTableModel(
                new String[]{
                    "NumFactura", "Fecha", "Cliente",
                    "Consultas", "DetalleFactura", "Tratamientos",
                    "Subtotal", "DescuentoPct", "MontoDesc",
                    "IVA%", "MontoIVA", "Total"
                }, 0
        );
        tabla_factura.setModel(modeloFactura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_cliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_subtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_descuento = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txt_descuento = new javax.swing.JTextField();
        txt_iva = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_numerofactura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_detallefactura = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_factura = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_cliente = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        txt_montoiva = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla_consulta = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_tratamiento = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_buscarconsulta = new javax.swing.JButton();
        btn_tratamiento = new javax.swing.JButton();
        btn_detallefactura = new javax.swing.JButton();
        cb_fecha = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Factura");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_cliente.setText("Buscar Cliente");
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel9.setText("Subtotal:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 450, -1, -1));

        jLabel1.setText("Cédula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel10.setText("Descuento:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 490, -1, -1));

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel11.setText("Monto IVA:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 550, -1, -1));

        jLabel3.setText("Nº Factura:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 20, -1, -1));

        jLabel12.setText("Total:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 600, -1, -1));

        jLabel4.setText("Fecha:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, -1, -1));

        txt_subtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subtotalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 450, 171, -1));

        jLabel5.setText("Cliente:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel6.setText("Detalle Factura:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, -1));

        cmb_descuento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cmb_descuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_descuentoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 490, 60, -1));

        jLabel13.setText("%");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 490, -1, -1));
        getContentPane().add(txt_descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 490, 86, -1));
        getContentPane().add(txt_iva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 520, 168, -1));

        txt_cedula.setEditable(false);
        getContentPane().add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 131, -1));
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 600, 168, -1));

        txt_nombre.setEditable(false);
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 131, -1));

        txt_numerofactura.setEditable(false);
        getContentPane().add(txt_numerofactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 20, 143, -1));

        tabla_detallefactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_detallefactura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 100, 677, 149));

        tabla_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla_factura);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 1630, 211));

        tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tabla_cliente);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 620, 149));

        jLabel14.setText("IVA:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 520, -1, -1));
        getContentPane().add(txt_montoiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 550, 168, -1));

        tabla_consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tabla_consulta);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 620, 132));

        tabla_tratamiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tabla_tratamiento);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 677, 132));

        jLabel7.setText("Consulta:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel8.setText("Tratamiento:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 310, -1, -1));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, 147, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 143, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, -1, -1));

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 620, 124, -1));

        btn_buscarconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscarconsulta.setText("Buscar Consulta");
        btn_buscarconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarconsultaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscarconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        btn_tratamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_tratamiento.setText("Buscar Tratamiento");
        btn_tratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tratamientoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 450, -1, 40));

        btn_detallefactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_detallefactura.setText("Buscar Detalle Factura");
        btn_detallefactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_detallefacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_detallefactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, -1, -1));
        getContentPane().add(cb_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
        if (tbl_editing()) {
            return;
        }
        Cliente cli = new Cliente();
        if (!cli.mtd_buscar()) {
            return;
        }
        // sólo agregar/seleccionar en tabla
        if (!existeRegistro(modeloCliente, cli.getCedula())) {
            modeloCliente.addRow(new Object[]{
                cli.getCedula(), cli.getNombre(), cli.getDireccion(), cli.getTelefono(), cli.getEmail(), sdf.format(cli.getFechaRegistro())
            });
        }
        int fila = modeloCliente.getRowCount() - 1;
        tabla_cliente.setRowSelectionInterval(fila, fila);
    }

    private boolean tbl_editing() {
        if (cmb_descuento.isPopupVisible()) {
            return false;
        }
        // no restrict here
        return false;
    }//GEN-LAST:event_btn_clienteActionPerformed

    /**
     * Comprueba si en el modelo 'm' ya hay una fila cuya primera columna
     * (índice 0) coincide con 'clave'
     */

    private void txt_subtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subtotalActionPerformed

    }//GEN-LAST:event_txt_subtotalActionPerformed

    private void cmb_descuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_descuentoActionPerformed

        recalcular();
    }//GEN-LAST:event_cmb_descuentoActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
       if (editModeFactura) {
        JOptionPane.showMessageDialog(this,
            "Termina la edición antes de agregar una nueva factura.",
            "Modo edición activo", JOptionPane.WARNING_MESSAGE);
        return;
    }

    if (!validarFactura()) return;

    String num = txt_numerofactura.getText().trim();
    Date fecha = cb_fecha.getDate();
    Cliente cli = leerClienteSeleccionado();

    if (cli == null || cli.getCedula().trim().isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Selecciona un cliente válido antes de continuar.",
            "Cliente no válido", JOptionPane.WARNING_MESSAGE);
        return;
    }

    List<DetalleFactura> detalles = new ArrayList<>();

    // Consultas
    for (int i = 0; i < modeloConsulta.getRowCount(); i++) {
        String cod = modeloConsulta.getValueAt(i, 0).toString();
        String desc = modeloConsulta.getValueAt(i, 1).toString();
        double precio = Double.parseDouble(modeloConsulta.getValueAt(i, 3).toString());
        detalles.add(new DetalleFactura(cod, desc, 1, precio));
    }

    // Tratamientos
    for (int i = 0; i < modeloTratamiento.getRowCount(); i++) {
        String cod = modeloTratamiento.getValueAt(i, 0).toString();
        String desc = modeloTratamiento.getValueAt(i, 1).toString();
        int cantidad = Integer.parseInt(modeloTratamiento.getValueAt(i, 2).toString());
        double precio = Double.parseDouble(modeloTratamiento.getValueAt(i, 3).toString());
        detalles.add(new DetalleFactura(cod, desc, cantidad, precio));
    }

    if (detalles.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Debe agregar al menos una consulta o tratamiento.",
            "Detalle vacío", JOptionPane.WARNING_MESSAGE);
        return;
    }

    double descPct = Double.parseDouble(cmb_descuento.getSelectedItem().toString());
    double ivaPct = Double.parseDouble(txt_iva.getText().trim());

    Factura f = new Factura(num, fecha, cli, detalles, descPct, ivaPct);

    // ————— ABRIR DIALOGO PARA GUARDAR FACTURA.TXT —————
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Selecciona la carpeta donde guardar la factura");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) {
        JOptionPane.showMessageDialog(this, "No se seleccionó carpeta. Cancelado.");
        return;
    }

    File carpeta = chooser.getSelectedFile();
    File archivoFactura = new File(carpeta, "factura_" + num + ".txt");
    f.setArchivo(archivoFactura);

    if (!f.mtd_guardar()) {
        JOptionPane.showMessageDialog(this,
            "Error al guardar la factura. Verifica los datos.",
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    modeloFactura.addRow(new Object[]{
        f.getNumeroFactura(),
        sdf.format(f.getFecha()),
        cli.getCedula() + " - " + cli.getNombre(),
        modeloConsulta.getRowCount(),
        detalles.size(),
        modeloTratamiento.getRowCount(),
        String.format(Locale.US, "%.2f", f.getSubtotal()),
        String.format(Locale.US, "%.2f", f.getDescuentoPct()),
        String.format(Locale.US, "%.2f", f.getMontoDescuento()),
        String.format(Locale.US, "%.2f", f.getIvaPct()),
        String.format(Locale.US, "%.2f", f.getMontoIva()),
        String.format(Locale.US, "%.2f", f.getTotal())
    });

    JOptionPane.showMessageDialog(this,
        "Factura guardada correctamente:\n" + archivoFactura.getAbsolutePath(),
        "Éxito", JOptionPane.INFORMATION_MESSAGE);

    limpiarFactura();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        if (editMode) {
            JOptionPane.showMessageDialog(this,
                    "No puede eliminar mientras edita.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = tabla_factura.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                    "Seleccione una fila de la factura para eliminar.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String numFac = modeloFactura.getValueAt(fila, 0).toString();
        Factura f = new Factura();
        f.setNumeroFactura(numFac);
        if (!f.mtd_eliminar()) {
            JOptionPane.showMessageDialog(this,
                    "No se pudo eliminar el archivo de factura.",
                    "Error I/O",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        modeloFactura.removeRow(fila);
        JOptionPane.showMessageDialog(this,
                "Factura eliminada correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (!editMode) {
            // --- Entrar en modo edición ---
            int fila = tabla_factura.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(this,
                        "Seleccione una factura para editar.",
                        "Aviso",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            // Cargo datos de la tabla al formulario
            txt_numerofactura.setText(modeloFactura.getValueAt(fila, 0).toString());
            try {
                Date d = sdf.parse(modeloFactura.getValueAt(fila, 1).toString());
                cb_fecha.setDate(d);
            } catch (ParseException e) {
                cb_fecha.setDate(new Date());
            }
            // Cargo cliente (queda siempre seleccionado en la tabla de cliente)
            String cliCed = modeloFactura.getValueAt(fila, 2).toString()
                    .split(" - ")[0];
            // Busco y cargo en el sub-formulario de cliente
            Cliente cli = new Cliente();
            cli.setCedula(cliCed);
            cli.mtd_buscar();
            modeloCliente.setRowCount(0);
            modeloCliente.addRow(new Object[]{
                cli.getCedula(),
                cli.getNombre(),
                cli.getDireccion(),
                cli.getTelefono(),
                cli.getEmail(),
                sdf.format(cli.getFechaRegistro())
            });

            // Cargo detalle de línea a tabla_detallefactura
            modeloDetFactura.setRowCount(0);
            Factura f = new Factura();
            f.setNumeroFactura(txt_numerofactura.getText().trim());
            f.mtd_buscar();  // ya llenó f.getDetalles()
            for (DetalleFactura d : f.getDetalles()) {
                modeloDetFactura.addRow(new Object[]{
                    d.getCodigoServicio(),
                    d.getDescripcionServicio(),
                    d.getCantidadSesiones(),
                    d.getPrecioUnitario(),
                    d.getTotalLinea()
                });
            }

            // Totales
            txt_subtotal.setText(String.valueOf(f.getSubtotal()));
            cmb_descuento.setSelectedItem(String.valueOf(f.getDescuentoPct()));
            txt_descuento.setText(String.valueOf(f.getMontoDescuento()));
            txt_iva.setText(String.valueOf(f.getIvaPct()));
            txt_montoiva.setText(String.valueOf(f.getMontoIva()));
            txt_total.setText(String.valueOf(f.getTotal()));

            editMode = true;
            editRow = fila;
            btn_editar.setText("Guardar");
            btn_agregar.setEnabled(false);
            btn_eliminar.setEnabled(false);
            btn_buscar.setEnabled(false);
        } else {
            // --- Guardar cambios ---
            if (!validarFactura()) {
                return;
            }

            // Reconstruyo y sobrescribo
            String numFac = txt_numerofactura.getText().trim();
            Date fecha = cb_fecha.getDate();
            Cliente cli = leerClienteSeleccionado();
            List<DetalleFactura> detalles = leerDetallesFactura();
            double descPct = Double.parseDouble(cmb_descuento.getSelectedItem().toString());
            double ivaPct = Double.parseDouble(txt_iva.getText().trim());

            Factura f = new Factura(numFac, fecha, cli,
                    detalles.toArray(new DetalleFactura[0]),
                    descPct, ivaPct);
            if (!f.mtd_guardar()) {
                JOptionPane.showMessageDialog(this,
                        "Error al actualizar factura.",
                        "Error I/O",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Actualizo la fila en tabla_factura
            modeloFactura.setValueAt(f.getNumeroFactura(), editRow, 0);
            modeloFactura.setValueAt(sdf.format(f.getFecha()), editRow, 1);
            modeloFactura.setValueAt(cli.getCedula() + "-" + cli.getNombre(), editRow, 2);
            modeloFactura.setValueAt(f.getSubtotal(), editRow, 3);
            modeloFactura.setValueAt(f.getDescuentoPct(), editRow, 4);
            modeloFactura.setValueAt(f.getIvaPct(), editRow, 5);
            modeloFactura.setValueAt(f.getMontoIva(), editRow, 6);
            modeloFactura.setValueAt(f.getTotal(), editRow, 7);

            JOptionPane.showMessageDialog(this,
                    "Factura actualizada correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE);

            // Salgo de modo edición
            editMode = false;
            editRow = -1;
            btn_editar.setText("Editar");
            btn_agregar.setEnabled(true);
            btn_eliminar.setEnabled(true);
            btn_buscar.setEnabled(true);
            limpiarFactura();
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_buscarconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarconsultaActionPerformed
       if (editModeFactura) {
        JOptionPane.showMessageDialog(this,
                "Termina la edicion antes de buscar una consulta.",
                "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Seleccionar consulta");
    chooser.setFileFilter(new FileNameExtensionFilter("Texto (*.txt)", "txt"));
    if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
        return; // usuario canceló
    }

    File archivo = chooser.getSelectedFile();
    Consulta con = new Consulta();
    if (!con.cargarDesdeArchivo(archivo)) {
        JOptionPane.showMessageDialog(this,
                "No se pudo cargar la consulta desde el archivo.",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    modeloConsulta.setRowCount(0); // limpiar antes de agregar
    modeloConsulta.addRow(new Object[]{
        con.getCodigo(), con.getMotivo(), con.getDuracionMinutos(), con.getPrecio()
    });

    recalcular();
    }//GEN-LAST:event_btn_buscarconsultaActionPerformed

    private void btn_tratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tratamientoActionPerformed
        if (editModeFactura) {
            JOptionPane.showMessageDialog(this,
                    "Termina la edición antes de buscar un tratamiento.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        modeloTratamiento.setRowCount(0);
        Tratamiento t = new Tratamiento();
        if (!t.mtd_buscar()) {
            return;
        }
        modeloTratamiento.addRow(new Object[]{
            t.getCodigo(), t.getDescripcion(), t.getCantidadSesiones(),
            t.getPrecioUnitario(), t.getTotalLinea()
        });
        recalcular();
    }

    private void limpiarCamposTratamiento() {
        tabla_tratamiento.clearSelection();
    }//GEN-LAST:event_btn_tratamientoActionPerformed

    private void btn_detallefacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_detallefacturaActionPerformed
        if (tbl_editing()) {
            return;
        }
        DetalleFactura d = new DetalleFactura();
        if (!d.mtd_buscar()) {
            return;
        }
        if (!existeRegistro(modeloDetFactura, d.getCodigoServicio())) {
            modeloDetFactura.addRow(new Object[]{d.getCodigoServicio(), d.getDescripcionServicio(), d.getCantidadSesiones(), d.getPrecioUnitario(), d.getTotalLinea()});
        }
        tabla_detallefactura.setRowSelectionInterval(modeloDetFactura.getRowCount() - 1, modeloDetFactura.getRowCount() - 1);
    }//GEN-LAST:event_btn_detallefacturaActionPerformed

    private void limpiarCamposDetFactura() {
        tabla_detallefactura.clearSelection();
    }
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if (editMode) {
            JOptionPane.showMessageDialog(this,
                    "Termine la edición antes de buscar.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        limpiarFactura();

        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Buscar Factura (.txt)");
        chooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File file = chooser.getSelectedFile();
        String name = file.getName();
        // Extraer número de factura de “factura_XXX.txt”
        String prefix = "factura_";
        String suffix = ".txt";
        String numFac;
        if (name.startsWith(prefix) && name.endsWith(suffix)) {
            numFac = name.substring(prefix.length(), name.length() - suffix.length());
        } else {
            numFac = name.replaceFirst("\\.txt$", "");
        }
        txt_numerofactura.setText(numFac);

        // Leer el contenido
        Factura f = new Factura();
        f.setNumeroFactura(numFac);
        if (!f.mtd_buscar()) {
            JOptionPane.showMessageDialog(this,
                    "No se encontró o no se pudo leer la factura.",
                    "Error I/O",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Cargo Cliente
        Cliente cli = new Cliente();
        cli.setCedula(f.getCliente().getCedula());
        cli.mtd_buscar();
        modeloCliente.addRow(new Object[]{
            cli.getCedula(),
            cli.getNombre(),
            cli.getDireccion(),
            cli.getTelefono(),
            cli.getEmail(),
            sdf.format(cli.getFechaRegistro())
        });

        // Cargo DetalleFactura
        for (DetalleFactura d : f.getDetalles()) {
            modeloDetFactura.addRow(new Object[]{
                d.getCodigoServicio(),
                d.getDescripcionServicio(),
                d.getCantidadSesiones(),
                d.getPrecioUnitario(),
                d.getTotalLinea()
            });
        }

        // Totales
        cb_fecha.setDate(f.getFecha());
        txt_subtotal.setText(String.valueOf(f.getSubtotal()));
        cmb_descuento.setSelectedItem(String.valueOf(f.getDescuentoPct()));
        txt_descuento.setText(String.valueOf(f.getMontoDescuento()));
        txt_iva.setText(String.valueOf(f.getIvaPct()));
        txt_montoiva.setText(String.valueOf(f.getMontoIva()));
        txt_total.setText(String.valueOf(f.getTotal()));

        // Y añado una fila en la tabla de factura históricas
        modeloFactura.addRow(new Object[]{
            f.getNumeroFactura(),
            sdf.format(f.getFecha()),
            cli.getCedula() + "-" + cli.getNombre(),
            f.getSubtotal(),
            f.getDescuentoPct(),
            f.getIvaPct(),
            f.getMontoIva(),
            f.getTotal()
        });
        int fila = modeloFactura.getRowCount() - 1;
        tabla_factura.setRowSelectionInterval(fila, fila);
    }//GEN-LAST:event_btn_buscarActionPerformed

// ————— Limpia todo el formulario de Factura para un nuevo ingreso —————
    private void limpiarFactura() {
        // Encabezado
        txt_numerofactura.setText("");
        cb_fecha.setDate(new Date());
        txt_cedula.setText("");
        txt_nombre.setText("");

        // Tablas auxiliares
        modeloCliente.setRowCount(0);
        modeloConsulta.setRowCount(0);
        modeloTratamiento.setRowCount(0);
        modeloDetFactura.setRowCount(0);

        // Totales
        txt_subtotal.setText("");
        cmb_descuento.setSelectedIndex(0);
        txt_descuento.setText("");
        txt_iva.setText("");
        txt_montoiva.setText("");
        txt_total.setText("");

        // Tabla histórica de facturas (si quieres empezar vacía cada vez)
        // modeloFactura.setRowCount(0);
    }

    private List<DetalleFactura> leerDetallesFactura() {
        List<DetalleFactura> lista = new ArrayList<>();
        // Asumo que tu DefaultTableModel de detalle factura está en la variable modeloDetFactura
        for (int i = 0; i < modeloDetFactura.getRowCount(); i++) {
            String codigo = modeloDetFactura.getValueAt(i, 0).toString();
            String descripcion = modeloDetFactura.getValueAt(i, 1).toString();
            int cantidad = Integer.parseInt(modeloDetFactura.getValueAt(i, 2).toString());
            double precio = Double.parseDouble(modeloDetFactura.getValueAt(i, 3).toString());
            // El constructor de DetalleFactura recibe (código, desc, cantidad, precioUnitario)
            lista.add(new DetalleFactura(codigo, descripcion, cantidad, precio));
        }
        return lista;
    }

    private void recalcular() {
        double subtotal = 0;

        // 1) Sumar precios de consulta (columna 3)
        for (int i = 0; i < modeloConsulta.getRowCount(); i++) {
            Object val = modeloConsulta.getValueAt(i, 3);
            subtotal += (val instanceof Number)
                    ? ((Number) val).doubleValue()
                    : Double.parseDouble(val.toString());
        }

        // 2) Sumar totales de tratamiento (columna 4)
        for (int i = 0; i < modeloTratamiento.getRowCount(); i++) {
            Object val = modeloTratamiento.getValueAt(i, 4);
            subtotal += (val instanceof Number)
                    ? ((Number) val).doubleValue()
                    : Double.parseDouble(val.toString());
        }

        // Mostrar subtotal
        txt_subtotal.setText(String.format("%.2f", subtotal));

        // 3) Descuento
        int descPct = Integer.parseInt(cmb_descuento.getSelectedItem().toString());
        double montoDesc = subtotal * descPct / 100.0;
        txt_descuento.setText(String.format("%.2f", montoDesc));

        // 4) Base y IVA fijo al 15%
        double base = subtotal - montoDesc;
        double ivaPct = 15.0;
        txt_iva.setText(String.format("%.0f", ivaPct));         // campo de IVA%
        double montoIva = base * ivaPct / 100.0;
        txt_montoiva.setText(String.format("%.2f", montoIva));

        // 5) Total final
        double total = base + montoIva;
        txt_total.setText(String.format("%.2f", total));
    }

    private void actualizarMontos() {
        double subtotal = 0;
        try {
            subtotal = Double.parseDouble(txt_subtotal.getText().trim());
        } catch (NumberFormatException e) {
            // si no es número, lo tomamos como 0
        }

        // % de descuento seleccionado
        double descPct = 0;
        try {
            descPct = Double.parseDouble(cmb_descuento.getSelectedItem().toString());
        } catch (Exception e) {
        }

        double montoDesc = subtotal * descPct / 100.0;
        double base = subtotal - montoDesc;

        // IVA fijo 15%
        double ivaPct = 15.0;
        double montoIva = base * ivaPct / 100.0;
        double total = base + montoIva;

        // actualizar campos
        txt_descuento.setText(String.format("%.2f", montoDesc));
        txt_iva.setText(String.format("%.0f", ivaPct));    // muestra "15"
        txt_montoiva.setText(String.format("%.2f", montoIva));
        txt_total.setText(String.format("%.2f", total));
    }

    private boolean validarFactura() {
        if (txt_numerofactura.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Número de factura vacío.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (tabla_cliente.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un cliente.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (modeloDetFactura.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "No hay detalle de factura.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    private Cliente leerClienteSeleccionado() {
        int f = tabla_cliente.getSelectedRow();
        String ced = modeloCliente.getValueAt(f, 0).toString();
        Cliente cli = new Cliente();
        cli.setCedula(ced);
        cli.mtd_buscar();
        return cli;
    }

    private boolean existeRegistro(DefaultTableModel model, String clave) {
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 0).equals(clave)) {
                return true;
            }
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_buscarconsulta;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_detallefactura;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_tratamiento;
    private org.jdesktop.swingx.JXDatePicker cb_fecha;
    private javax.swing.JComboBox<String> cmb_descuento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tabla_cliente;
    private javax.swing.JTable tabla_consulta;
    private javax.swing.JTable tabla_detallefactura;
    private javax.swing.JTable tabla_factura;
    private javax.swing.JTable tabla_tratamiento;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_descuento;
    private javax.swing.JTextField txt_iva;
    private javax.swing.JTextField txt_montoiva;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_numerofactura;
    private javax.swing.JTextField txt_subtotal;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
