/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CosmediaSpa.Formularios;

import CosmediaSpa.Empleado;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
/**
 *
 * @author vicom
 */
public class frm_empleado extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private SimpleDateFormat    sdf      = new SimpleDateFormat("yyyy-MM-dd");
    private boolean             editMode = false;
    private int                 editRow  = -1;
  
    public frm_empleado() {
        initComponents();
        inicializarTabla();
    }
    
    private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
            new String[]{"Cédula","Nombre","Teléfono","Email","FechaContratación"}, 0
        );
        tabla_empleado.setModel(modeloTabla);
    }
    
    private void limpiarCampos() {
    txt_cedula.setText("");
    txt_nombre.setText("");
    txt_telefono.setText("");
    txt_email.setText("");
    cb_fechadecontratacion.setDate(null);
    tabla_empleado.clearSelection();
}
    
    private Empleado leerEmpleadoDesdeCampos() {
    // El date-picker ya devuelve un Date
    Date fecha = cb_fechadecontratacion.getDate();
    return new Empleado(
        txt_cedula.getText().trim(),
        txt_nombre.getText().trim(),
        txt_telefono.getText().trim(),
        txt_email.getText().trim(),
        fecha
    );
}
    
    private boolean validarCampos() {
         String ced = txt_cedula.getText().trim();
    if (!ced.matches("\\d{10}") || !new Empleado().validarCedula(ced)) {
        JOptionPane.showMessageDialog(this, "Ingrese una cédula válida (10 dígitos).");
        return false;
    }
    String nom = txt_nombre.getText().trim();
    if (nom.isEmpty()) {
        JOptionPane.showMessageDialog(this, "El nombre no puede estar vacío.");
        return false;
    }
    String tel = txt_telefono.getText().trim();
    if (!tel.matches("\\d{7,10}") || !new Empleado().validarTelefono(tel)) {
        JOptionPane.showMessageDialog(this, "Teléfono inválido.");
        return false;
    }
    String mail = txt_email.getText().trim();
    if (!new Empleado().validarEmail(mail)) {
        JOptionPane.showMessageDialog(this, "Email inválido.");
        return false;
    }
    Date fc = cb_fechadecontratacion.getDate();
    if (fc == null) {
        JOptionPane.showMessageDialog(this, "Seleccione la fecha de contratación.");
        return false;
    }
    return true;
    }

    private void volcarTablaAFuentes(int fila) {
        txt_cedula.setText(   modeloTabla.getValueAt(fila, 0).toString());
    txt_nombre.setText(   modeloTabla.getValueAt(fila, 1).toString());
    txt_telefono.setText( modeloTabla.getValueAt(fila, 2).toString());
    txt_email.setText(    modeloTabla.getValueAt(fila, 3).toString());
    // Parsear la cadena de la tabla al date-picker
    try {
        Date d = sdf.parse(modeloTabla.getValueAt(fila, 4).toString());
        cb_fechadecontratacion.setDate(d);
    } catch (ParseException ex) {
        cb_fechadecontratacion.setDate(null);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_agregar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_empleado = new javax.swing.JTable();
        txt_telefono = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_fechadecontratacion = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Empleado");

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cedula:");

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefono:");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel4.setText("E-mail:");

        tabla_empleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_empleado);

        jLabel5.setText("Fecha de Contratacion:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(txt_telefono)
                                    .addComponent(txt_nombre)
                                    .addComponent(txt_cedula)))
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_fechadecontratacion, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_agregar)
                                .addGap(28, 28, 28)
                                .addComponent(btn_editar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_eliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscar)))
                        .addGap(73, 73, 73)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_fechadecontratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_editar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_buscar))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
      if (editMode) {
        JOptionPane.showMessageDialog(this, "Termine la edición antes de agregar otro.");
        return;
    }
    if (!validarCampos()) return;

    Empleado emp = leerEmpleadoDesdeCampos();
    if (!emp.mtd_guardar()) {
        JOptionPane.showMessageDialog(this,
            "Error al guardar archivo de empleado.",
            "Error I/O",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    if (existeRegistro(emp.getCedula())) {
        JOptionPane.showMessageDialog(this,
            "El empleado ya está en la tabla.",
            "Aviso",
            JOptionPane.INFORMATION_MESSAGE
        );
        limpiarCampos();
        return;
    }

    modeloTabla.addRow(new Object[]{
        emp.getCedula(),
        emp.getNombre(),
        emp.getTelefono(),
        emp.getEmail(),
        sdf.format(emp.getFechaContratacion())
    });
    JOptionPane.showMessageDialog(this,
        "Empleado guardado en archivo y tabla.",
        "Éxito",
        JOptionPane.INFORMATION_MESSAGE
    );
    limpiarCampos();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
     if (!editMode) {
        int fila = tabla_empleado.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this,
                "Seleccione una fila para editar.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
        volcarTablaAFuentes(fila);
        editMode = true;
        editRow  = fila;
        btn_editar.setText("GUARDAR");
        btn_agregar.setEnabled(false);
        btn_eliminar.setEnabled(false);
        btn_buscar.setEnabled(false);
    } else {
        if (!validarCampos()) return;
        Empleado emp = leerEmpleadoDesdeCampos();
        if (!emp.mtd_guardar()) {
            JOptionPane.showMessageDialog(this,
                "Error al actualizar archivo.",
                "Error I/O",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        // actualizamos fila
        modeloTabla.setValueAt(emp.getCedula(), editRow, 0);
        modeloTabla.setValueAt(emp.getNombre(), editRow, 1);
        modeloTabla.setValueAt(emp.getTelefono(), editRow, 2);
        modeloTabla.setValueAt(emp.getEmail(), editRow, 3);
        modeloTabla.setValueAt(sdf.format(emp.getFechaContratacion()), editRow, 4);

        JOptionPane.showMessageDialog(this,
            "Empleado actualizado en archivo y tabla.",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE
        );
        // salimos de modo edición
        editMode = false;
        editRow  = -1;
        btn_editar.setText("EDITAR");
        btn_agregar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_buscar.setEnabled(true);
        limpiarCampos();
    }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
  if (editMode) {
        JOptionPane.showMessageDialog(this,
            "No puede eliminar mientras edita.",
            "Aviso",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    int fila = tabla_empleado.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(this,
            "Seleccione una fila para eliminar.",
            "Aviso",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    String ced = modeloTabla.getValueAt(fila, 0).toString();
    Empleado emp = new Empleado();
    emp.setCedula(ced);
    if (!emp.mtd_eliminar()) {
        JOptionPane.showMessageDialog(this,
            "No se pudo eliminar archivo de empleado.",
            "Error I/O",
            JOptionPane.ERROR_MESSAGE
        );
        return;
    }
    modeloTabla.removeRow(fila);
    limpiarCampos();
    JOptionPane.showMessageDialog(this,
        "Empleado eliminado de archivo y tabla.",
        "Éxito",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       if (editMode) {
        JOptionPane.showMessageDialog(this,
            "No puede buscar mientras edita.",
            "Aviso",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }
    limpiarCampos();
    Empleado emp = new Empleado();
    if (!emp.mtd_buscar()) {
        JOptionPane.showMessageDialog(this,
            "No se cargó ningún empleado o se canceló.",
            "Información",
            JOptionPane.INFORMATION_MESSAGE
        );
        return;
    }
   txt_cedula.setText(emp.getCedula());
txt_nombre.setText(emp.getNombre());
txt_telefono.setText(emp.getTelefono());
txt_email.setText(emp.getEmail());
// Poner la fecha en el JXDatePicker:
cb_fechadecontratacion.setDate(emp.getFechaContratacion());

    if (existeRegistro(emp.getCedula())) {
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            if (modeloTabla.getValueAt(i, 0).equals(emp.getCedula())) {
                tabla_empleado.setRowSelectionInterval(i, i);
                break;
            }
        }
    } else {
        modeloTabla.addRow(new Object[]{
            emp.getCedula(),
            emp.getNombre(),
            emp.getTelefono(),
            emp.getEmail(),
            sdf.format(emp.getFechaContratacion())
        });
        int nf = modeloTabla.getRowCount() - 1;
        tabla_empleado.setRowSelectionInterval(nf, nf);
    }
     editMode = true;
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        if (modeloTabla.getValueAt(i, 0).equals(emp.getCedula())) {
            editRow = i;
            break;
        }
    }
    btn_editar.setText("GUARDAR");
    }//GEN-LAST:event_btn_buscarActionPerformed

    private boolean existeRegistro(String cedula) {
    for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        if (modeloTabla.getValueAt(i, 0).equals(cedula)) {
            return true;
        }
    }
    return false;
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private org.jdesktop.swingx.JXDatePicker cb_fechadecontratacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_empleado;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
