package CosmediaSpa.Formularios;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
import CosmediaSpa.Cliente;
import CosmediaSpa.Factura;
import CosmediaSpa.Pago;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author vicom
 */
public class frm_pago extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloFactura;
    private DefaultTableModel modeloPago;
    private final SimpleDateFormat sdfFactura = new SimpleDateFormat("yyyy-MM-dd");
    private final SimpleDateFormat sdfPago = new SimpleDateFormat("yyyy-MM-dd");
    private boolean editMode = false;
    private int editRow = -1;
    private File archivoEditando = null;

    public frm_pago() {
        initComponents();
        inicializarTablas();

    }

    private void inicializarTablas() {
        // Tabla de facturas (with Total column)
        modeloFactura = new DefaultTableModel(
                new String[]{
                    "NumFactura", "Fecha", "Cliente",
                    "Consultas", "DetalleFactura", "Tratamientos",
                    "Subtotal", "DescuentoPct", "MontoDesc",
                    "IVA%", "MontoIVA", "Total"
                }, 0
        );
        tabla_factura.setModel(modeloFactura);

        // Tabla de pagos
        modeloPago = new DefaultTableModel(
                new String[]{
                    "CodigoPago", "N°Factura", "FechaPago",
                    "Metodo", "Estado", "Observaciones", "Monto"
                }, 0
        );
        tabla_pagos.setModel(modeloPago);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_eliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_factura = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txt_codigos = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla_pagos = new javax.swing.JTable();
        btn_buscarFact = new javax.swing.JButton();
        txt_numFacturas = new javax.swing.JTextField();
        btn_eliminarFact = new javax.swing.JButton();
        cb_fechapagos = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        cmb_metodoPago = new javax.swing.JComboBox<>();
        txt_monto = new javax.swing.JTextField();
        cmb_estadoPago = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_buscar1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Pago");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 366, -1, -1));

        tabla_factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tabla_factura);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1591, 163));

        jLabel7.setText("Observaciones:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 520, -1, -1));
        getContentPane().add(txt_codigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 260, 143, -1));

        tabla_pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabla_pagos);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1603, 190));

        btn_buscarFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscarFact.setText("BUSCAR");
        btn_buscarFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarFactActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscarFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 175, -1, -1));
        getContentPane().add(txt_numFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 317, 143, -1));

        btn_eliminarFact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminarFact.setText("ELIMINAR");
        btn_eliminarFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarFactActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminarFact, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 175, -1, -1));
        getContentPane().add(cb_fechapagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 373, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Monto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1460, 186, -1, -1));

        cmb_metodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta de Credito", "Transferencia" }));
        cmb_metodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_metodoPagoActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_metodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 431, 143, -1));
        getContentPane().add(txt_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1508, 183, 89, -1));

        cmb_estadoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Pagado" }));
        getContentPane().add(cmb_estadoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 480, 143, -1));

        jLabel2.setText("Codigo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 263, -1, -1));

        txt_observaciones.setColumns(20);
        txt_observaciones.setRows(5);
        jScrollPane1.setViewportView(txt_observaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 520, -1, -1));

        jLabel3.setText("Numero de Facturas");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 320, -1, -1));

        jLabel4.setText("Fecha de Pago:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 377, -1, -1));

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 252, 119, -1));

        jLabel5.setText("Metodo de Pago:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 434, -1, -1));

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 309, 119, -1));

        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 483, -1, -1));

        btn_buscar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar1.setText("BUSCAR");
        btn_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 423, 119, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarFactActionPerformed
        if (editMode) {
            JOptionPane.showMessageDialog(this,
                    "No puede buscar factura mientras edita un pago.",
                    "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1) Una sola vez abrimos el chooser
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Abrir Factura (.txt)");
        chooser.setFileFilter(new FileNameExtensionFilter("Texto (*.txt)", "txt"));
        if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
            return; // canceló
        }
        File fichero = chooser.getSelectedFile();

        // 2) Cargar factura desde archivo
        Factura f = new Factura();
        if (!f.cargarDesdeArchivo(fichero)) {

            return; // error interno ya mostrado
        }

        // 3) Preparar texto de cliente
        Cliente cli = f.getCliente();
        String clienteTexto;
        if (cli != null && cli.getCedula() != null && !cli.getCedula().isEmpty()) {
            clienteTexto = cli.getCedula()
                    + (cli.getNombre() != null && !cli.getNombre().isEmpty()
                    ? " – " + cli.getNombre()
                    : "");
        } else {
            clienteTexto = "Cliente no encontrado";
        }

        // 4) Rellenar tabla y formulario
        modeloFactura.setRowCount(0);
        modeloFactura.addRow(new Object[]{
            f.getNumeroFactura(),
            sdfFactura.format(f.getFecha()),
            clienteTexto,
            f.getDetalles().size(), // consultas
            f.getDetalles().size(), // detalleFactura
            f.getDetalles().size(), // tratamientos (ajusta si cambias)
            String.format(Locale.US, "%.2f", f.getSubtotal()),
            String.format(Locale.US, "%.2f", f.getDescuentoPct()),
            String.format(Locale.US, "%.2f", f.getMontoDescuento()),
            String.format(Locale.US, "%.2f", f.getIvaPct()),
            String.format(Locale.US, "%.2f", f.getMontoIva()),
            String.format(Locale.US, "%.2f", f.getTotal())
        });

        txt_numFacturas.setText(f.getNumeroFactura());
        cb_fechapagos.setDate(f.getFecha());
        txt_monto.setText(String.format(Locale.US, "%.2f", f.getTotal()));
    }//GEN-LAST:event_btn_buscarFactActionPerformed

    private void btn_eliminarFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarFactActionPerformed

    }//GEN-LAST:event_btn_eliminarFactActionPerformed

    private void cmb_metodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_metodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_metodoPagoActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        if (!validarFormulario()) return;

    Pago p = new Pago(
        txt_codigos.getText().trim(),
        txt_numFacturas.getText().trim(),
        cb_fechapagos.getDate(),
        cmb_metodoPago.getSelectedItem().toString(),
        cmb_estadoPago.getSelectedItem().toString(),
        txt_observaciones.getText().trim(),
        Double.parseDouble(txt_monto.getText().trim().replace(",","."))
    );

    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Guardar Pago (.txt)");
    chooser.setSelectedFile(new File("pago_" + p.getCodigoPago() + ".txt"));
    chooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));
    if (chooser.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;

    File archivo = chooser.getSelectedFile();
    if (!archivo.getName().toLowerCase().endsWith(".txt"))
        archivo = new File(archivo.getAbsolutePath()+".txt");

    p.setArchivo(archivo);
    if (!p.mtd_guardar()) return;

    // **Solo ahora** añadimos la fila a la tabla
    modeloPago.addRow(new Object[]{
        p.getCodigoPago(),
        p.getNumeroFactura(),
        sdfPago.format(p.getFechaPago()),
        p.getMetodoPago(),
        p.getEstado(),
        p.getObservaciones(),
        String.format(Locale.US, "%.2f", p.getMonto())
    });

    JOptionPane.showMessageDialog(this,
        "Pago guardado correctamente en archivo y tabla.",
        "Éxito", JOptionPane.INFORMATION_MESSAGE);
    limpiarCampos();
    }

    /**
     * Carga un pago existente para editar
     */
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {

    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
       if (!editMode) {
        // si no está en edición, delega a buscar
        btn_buscar1ActionPerformed(evt);
        return;
    }
    if (!validarFormulario()) return;

    Pago p = new Pago(
        txt_codigos.getText().trim(),
        txt_numFacturas.getText().trim(),
        cb_fechapagos.getDate(),
        cmb_metodoPago.getSelectedItem().toString(),
        cmb_estadoPago.getSelectedItem().toString(),
        txt_observaciones.getText().trim(),
        Double.parseDouble(txt_monto.getText().trim().replace(",","."))
    );

    p.setArchivo(archivoEditando);
    if (!p.mtd_guardar()) return;

    // refrescamos la fila editada
    modeloPago.setValueAt(p.getCodigoPago(),               editRow,0);
    modeloPago.setValueAt(p.getNumeroFactura(),            editRow,1);
    modeloPago.setValueAt(sdfPago.format(p.getFechaPago()),editRow,2);
    modeloPago.setValueAt(p.getMetodoPago(),               editRow,3);
    modeloPago.setValueAt(p.getEstado(),                   editRow,4);
    modeloPago.setValueAt(p.getObservaciones(),            editRow,5);
    modeloPago.setValueAt(String.format(Locale.US,"%.2f",p.getMonto()), editRow,6);

    JOptionPane.showMessageDialog(this,
        "Pago actualizado correctamente.",
        "Éxito", JOptionPane.INFORMATION_MESSAGE);
    limpiarCampos();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       if (editMode) {
        JOptionPane.showMessageDialog(this,
            "No puede eliminar mientras edita.",
            "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }
    int fila = tabla_pagos.getSelectedRow();
    if (fila<0) {
        JOptionPane.showMessageDialog(this,
            "Seleccione un pago para eliminar.",
            "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Eliminar Pago (.txt)");
    chooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));
    if (chooser.showOpenDialog(this)!=JFileChooser.APPROVE_OPTION) return;

    File archivo = chooser.getSelectedFile();
    Pago p = new Pago();
    p.setArchivo(archivo);
    if (!p.mtd_eliminar()) return;

    modeloPago.removeRow(fila);
    JOptionPane.showMessageDialog(this,
        "Pago eliminado de disco y de la tabla.",
        "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar1ActionPerformed
        // 1) Si ya estás editando, no permitimos otro buscar
    if (editMode) {
        JOptionPane.showMessageDialog(this,
            "Ya está en modo edición. Termine o cancele antes de buscar otro pago.",
            "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2) Abrir JFileChooser para que el usuario elija dónde está el .txt de pago
    JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Abrir Pago (.txt)");
    chooser.setFileFilter(new FileNameExtensionFilter("Archivos de texto (*.txt)", "txt"));
    if (chooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
        return; // el usuario canceló
    }
    File archivo = chooser.getSelectedFile();
    if (!archivo.exists()) {
        JOptionPane.showMessageDialog(this,
            "El archivo no existe:\n" + archivo.getAbsolutePath(),
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 3) Cargar el pago desde el archivo elegido
    Pago p = new Pago();
    p.setArchivo(archivo);
    if (!p.mtd_buscar()) {
        // mtd_buscar ya mostró el error correspondiente
        return;
    }

    // 4) Volcar datos al formulario
    txt_codigos.setText(p.getCodigoPago());
    txt_numFacturas.setText(p.getNumeroFactura());
    cb_fechapagos.setDate(p.getFechaPago());
    cmb_metodoPago.setSelectedItem(p.getMetodoPago());
    cmb_estadoPago.setSelectedItem(p.getEstado());
    txt_observaciones.setText(p.getObservaciones());
    txt_monto.setText(String.format(Locale.US, "%.2f", p.getMonto()));

    // 5) Refrescar la tabla de pagos con **solo** este registro (o coméntalo si prefieres append)
    modeloPago.setRowCount(0);
    modeloPago.addRow(new Object[]{
        p.getCodigoPago(),
        p.getNumeroFactura(),
        sdfPago.format(p.getFechaPago()),
        p.getMetodoPago(),
        p.getEstado(),
        p.getObservaciones(),
        String.format(Locale.US, "%.2f", p.getMonto())
    });

    // 6) Preparar para editar este pago
    archivoEditando = archivo;
    editMode        = true;
    editRow         = modeloPago.getRowCount() - 1;  // fíjate la fila recién añadida
    tabla_pagos.setRowSelectionInterval(editRow, editRow);

    // 7) Ajustar botones
    btn_editar.setText("Guardar");
    btn_agregar.setEnabled(false);
    btn_eliminar.setEnabled(false);
    }//GEN-LAST:event_btn_buscar1ActionPerformed

    private void limpiarCampos() {
        txt_codigos.setText("");
        txt_numFacturas.setText("");
        cb_fechapagos.setDate(new Date());
        cmb_metodoPago.setSelectedIndex(0);
        cmb_estadoPago.setSelectedIndex(0);
        txt_observaciones.setText("");
        txt_monto.setText("");
        editMode = false;
        editRow = -1;
        btn_editar.setText("EDITAR");
        btn_agregar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_buscarFact.setEnabled(true);
    }

    private boolean validarFormulario() {
        String textoMonto = txt_monto.getText().trim().replace(",", ".");
        try {
            double m = Double.parseDouble(textoMonto);
            if (m < 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                    "Monto inválido.",
                    "Validación", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar1;
    private javax.swing.JButton btn_buscarFact;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_eliminarFact;
    private org.jdesktop.swingx.JXDatePicker cb_fechapagos;
    private javax.swing.JComboBox<String> cmb_estadoPago;
    private javax.swing.JComboBox<String> cmb_metodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabla_factura;
    private javax.swing.JTable tabla_pagos;
    private javax.swing.JTextField txt_codigos;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_numFacturas;
    private javax.swing.JTextArea txt_observaciones;
    // End of variables declaration//GEN-END:variables

}
