/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CosmediaSpa.Formularios;


import CosmediaSpa.DetalleFactura;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author vicom
 */
public class frm_detallefactura extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private boolean editMode = false;
    private int editRow = -1;

    public frm_detallefactura() {
        initComponents();
        inicializarTabla();
    }

     private void inicializarTabla() {
        modeloTabla = new DefaultTableModel(
            new Object[]{"CódigoServicio","Descripción","Cant. Sesiones","Precio Unit.","Total Línea"},
            0
        );
        tabla_detalles.setModel(modeloTabla);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_total = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_editar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_detalles = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_codigoservicio = new javax.swing.JTextField();
        txt_cantidadsesiones = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        txt_precio = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Detalle Factura");

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo de Servicio:");

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        jLabel2.setText("Descripcion Servicio:");

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad Sesiones:");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio Unitario:");

        tabla_detalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_detalles);

        jLabel5.setText("Total:");

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane2.setViewportView(txt_descripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_codigoservicio)
                            .addComponent(txt_cantidadsesiones)
                            .addComponent(txt_precio)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                            .addComponent(txt_total))
                        .addGap(72, 72, 72)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_agregar)
                        .addGap(28, 28, 28)
                        .addComponent(btn_editar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_eliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_buscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_codigoservicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_cantidadsesiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_agregar)
                            .addComponent(btn_editar)
                            .addComponent(btn_eliminar)
                            .addComponent(btn_buscar))))
                .addGap(158, 158, 158))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
     if (editMode) {
            JOptionPane.showMessageDialog(this, "Termine la edición antes de agregar otra línea.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCampos()) return;

        String codigo = txt_codigoservicio.getText().trim();
        String descripcion = txt_descripcion.getText().trim();
        int cantidad = Integer.parseInt(txt_cantidadsesiones.getText().trim());
        double precio = Double.parseDouble(txt_precio.getText().trim());

        DetalleFactura df = new DetalleFactura(codigo, descripcion, cantidad, precio);
        if (!df.mtd_guardar()) {
            JOptionPane.showMessageDialog(this, "Error al guardar el archivo de detalle.", "Error I/O", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Evitar duplicados por código
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            if (modeloTabla.getValueAt(i, 0).equals(codigo)) {
                JOptionPane.showMessageDialog(this, "Ya existe ese detalle en la tabla.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiarCampos();
                return;
            }
        }

        double total = df.getTotalLinea();
        modeloTabla.addRow(new Object[]{codigo, descripcion, cantidad, precio, total});
        JOptionPane.showMessageDialog(this, "Detalle guardado en archivo y tabla.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiarCampos();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
     if (!editMode) {
            int fila = tabla_detalles.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(this, "Seleccione una fila para editar.", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            // Cargar datos en campos
            txt_codigoservicio.setText(modeloTabla.getValueAt(fila, 0).toString());
            txt_descripcion.setText(modeloTabla.getValueAt(fila, 1).toString());
            txt_cantidadsesiones.setText(modeloTabla.getValueAt(fila, 2).toString());
            txt_precio.setText(modeloTabla.getValueAt(fila, 3).toString());
            txt_total.setText(modeloTabla.getValueAt(fila, 4).toString());

            editMode = true;
            editRow = fila;
            btn_editar.setText("GUARDAR");
            btn_agregar.setEnabled(false);
            btn_eliminar.setEnabled(false);
            btn_buscar.setEnabled(false);
        } else {
            // Guardar cambios
            if (!validarCampos()) return;

            String codigo = txt_codigoservicio.getText().trim();
            String descripcion = txt_descripcion.getText().trim();
            int cantidad = Integer.parseInt(txt_cantidadsesiones.getText().trim());
            double precio = Double.parseDouble(txt_precio.getText().trim());

            DetalleFactura df = new DetalleFactura(codigo, descripcion, cantidad, precio);
            if (!df.mtd_guardar()) {
                JOptionPane.showMessageDialog(this, "Error al actualizar el archivo de detalle.", "Error I/O", JOptionPane.ERROR_MESSAGE);
                return;
            }

            double total = df.getTotalLinea();
            modeloTabla.setValueAt(codigo,      editRow, 0);
            modeloTabla.setValueAt(descripcion, editRow, 1);
            modeloTabla.setValueAt(cantidad,    editRow, 2);
            modeloTabla.setValueAt(precio,      editRow, 3);
            modeloTabla.setValueAt(total,       editRow, 4);

            JOptionPane.showMessageDialog(this, "Detalle actualizado en archivo y tabla.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            btn_editar.setText("EDITAR");
            btn_agregar.setEnabled(true);
            btn_eliminar.setEnabled(true);
            btn_buscar.setEnabled(true);
            editMode = false;
            editRow = -1;
            limpiarCampos();
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       if (editMode) {
            JOptionPane.showMessageDialog(this, "No puede eliminar mientras edita.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = tabla_detalles.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione una fila para eliminar.", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String codigo = modeloTabla.getValueAt(fila, 0).toString();
        DetalleFactura df = new DetalleFactura();
        df.setCodigoServicio(codigo);
        if (!df.mtd_eliminar()) {
            JOptionPane.showMessageDialog(this, "No se pudo eliminar el archivo de detalle.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        modeloTabla.removeRow(fila);
        limpiarCampos();
        JOptionPane.showMessageDialog(this, "Detalle eliminado de archivo y tabla.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
      if (editMode) {
            JOptionPane.showMessageDialog(this, "No puede buscar mientras edita.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        DetalleFactura df = new DetalleFactura();
        if (!df.mtd_buscar()) {
            JOptionPane.showMessageDialog(this, "No se cargó ningún detalle o se canceló.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // Mostrar campos
        String codigo = df.getCodigoServicio();
        String descripcion = df.getDescripcionServicio();
        int cantidad = df.getCantidadSesiones();
        double precio = df.getPrecioUnitario();
        double total = df.getTotalLinea();

        txt_codigoservicio.setText(codigo);
        txt_descripcion.setText(descripcion);
        txt_cantidadsesiones.setText(String.valueOf(cantidad));
        txt_precio.setText(String.valueOf(precio));
        txt_total.setText(String.valueOf(total));

        // Evitar duplicados en la tabla
        boolean existe = false;
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            if (modeloTabla.getValueAt(i, 0).equals(codigo)) {
                existe = true;
                tabla_detalles.setRowSelectionInterval(i, i);
                break;
            }
        }
        if (!existe) {
            modeloTabla.addRow(new Object[]{codigo, descripcion, cantidad, precio, total});
            int nueva = modeloTabla.getRowCount() - 1;
            tabla_detalles.setRowSelectionInterval(nueva, nueva);
        }
        // pasar a modo edición
        editMode = true;
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
            if (modeloTabla.getValueAt(i, 0).equals(codigo)) {
                editRow = i;
                break;
            }
        }
        btn_editar.setText("GUARDAR");
        btn_agregar.setEnabled(false);
        btn_eliminar.setEnabled(false);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void limpiarCampos() {
        txt_codigoservicio.setText("");
        txt_descripcion.setText("");
        txt_cantidadsesiones.setText("");
        txt_precio.setText("");
        txt_total.setText("");
        tabla_detalles.clearSelection();
    }

    private boolean validarCampos() {
        if (txt_codigoservicio.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El código no puede estar vacío.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txt_descripcion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripción no puede estar vacía.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            int c = Integer.parseInt(txt_cantidadsesiones.getText().trim());
            if (c < 1) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Cantidad de sesiones inválida.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            double p = Double.parseDouble(txt_precio.getText().trim());
            if (p < 0) throw new NumberFormatException();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Precio unitario inválido.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla_detalles;
    private javax.swing.JTextField txt_cantidadsesiones;
    private javax.swing.JTextField txt_codigoservicio;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
