/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package CosmediaSpa.Formularios;

import CosmediaSpa.Proveedor;
import CosmediaSpa.Validacion;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
/**
 *
 * @author vicom
 */
public class frm_proveedor extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloProveedor;
    private boolean editMode = false;
    private int editRow = -1;

    public frm_proveedor() {
        initComponents();
        inicializarTabla();
    }

    private void inicializarTabla() {
        modeloProveedor = new DefaultTableModel(
            new Object[]{"Cédula","Nombre","Dirección","Teléfono","Email","FechaReg","CodProv","CodPostal","Saldo"},
            0
        );
        tabla_proveedor.setModel(modeloProveedor);
    }

    private void limpiarCampos() {
        txt_cedula.setText("");
        txt_nombre.setText("");
        txt_direccion.setText("");
        txt_telefono.setText("");
        txt_email.setText("");
        cb_fecharegistro.setDate(new Date());
        txt_codigoprovincia.setText("");
        txt_codigopostal.setText("");
        txt_saldo.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_proveedor = new javax.swing.JTable();
        btn_agregar = new javax.swing.JButton();
        txt_nombre = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_cedula = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_editar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_codigoprovincia = new javax.swing.JTextField();
        txt_codigopostal = new javax.swing.JTextField();
        txt_saldo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_fecharegistro = new org.jdesktop.swingx.JXDatePicker();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Proveedor");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifying-glass.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel4.setText("E-mail:");

        tabla_proveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla_proveedor);

        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/file-text.png"))); // NOI18N
        btn_agregar.setText("AGREGAR");
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cedula:");

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pencil.png"))); // NOI18N
        btn_editar.setText("EDITAR");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha de Registro:");

        jLabel2.setText("Nombre:");

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trash-simple.png"))); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefono:");

        jLabel6.setText("Direccion:");

        jLabel7.setText("Codigo Provincia:");

        jLabel8.setText("Codigo Postal:");

        jLabel9.setText("Saldo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txt_telefono)
                            .addComponent(txt_nombre)
                            .addComponent(txt_cedula)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_codigoprovincia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txt_codigopostal, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(txt_saldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(cb_fecharegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_agregar)
                .addGap(28, 28, 28)
                .addComponent(btn_editar)
                .addGap(18, 18, 18)
                .addComponent(btn_eliminar)
                .addGap(18, 18, 18)
                .addComponent(btn_buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cb_fecharegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codigoprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_codigopostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_agregar)
                    .addComponent(btn_editar)
                    .addComponent(btn_eliminar)
                    .addComponent(btn_buscar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
    if (editMode) {
            JOptionPane.showMessageDialog(this, "Termine la edición antes de buscar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        limpiarCampos();
        Proveedor p = new Proveedor();
        // se usa la cédula que esté en txt_cedula
        p.setCedula(txt_cedula.getText().trim());
        if (!p.mtd_buscar()) {
            JOptionPane.showMessageDialog(this, "No se cargó ningún proveedor.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        // volcar datos a campos
        txt_cedula.setText(p.getCedula());
        txt_nombre.setText(p.getNombre());
        txt_direccion.setText(p.getDireccion());
        txt_telefono.setText(p.getTelefono());
        txt_email.setText(p.getEmail());
        cb_fecharegistro.setDate(p.getFechaRegistro());
        txt_codigoprovincia.setText(p.getCodigoProvincia());
        txt_codigopostal.setText(p.getCodigoPostal());
        txt_saldo.setText(String.valueOf(p.getSaldo()));

        // buscar en tabla o agregar
        editMode = true;
        btn_editar.setText("GUARDAR");
        for (int i = 0; i < modeloProveedor.getRowCount(); i++) {
            if (modeloProveedor.getValueAt(i, 0).equals(p.getCedula())) {
                editRow = i;
                tabla_proveedor.setRowSelectionInterval(i, i);
                return;
            }
        }
        modeloProveedor.addRow(new Object[]{
            p.getCedula(), p.getNombre(), p.getDireccion(),
            p.getTelefono(), p.getEmail(),
            new java.text.SimpleDateFormat("yyyy-MM-dd").format(p.getFechaRegistro()),
            p.getCodigoProvincia(), p.getCodigoPostal(), p.getSaldo()
        });
        editRow = modeloProveedor.getRowCount() - 1;
        tabla_proveedor.setRowSelectionInterval(editRow, editRow);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
       if (editMode) {
            JOptionPane.showMessageDialog(this, "Termine la edición antes de agregar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCampos()) return;

        Proveedor p = new Proveedor(
            txt_cedula.getText().trim(),
            txt_nombre.getText().trim(),
            txt_direccion.getText().trim(),
            txt_telefono.getText().trim(),
            txt_email.getText().trim(),
            cb_fecharegistro.getDate(),
            txt_codigoprovincia.getText().trim(),
            txt_codigopostal.getText().trim(),
            Double.parseDouble(txt_saldo.getText().trim())
        );
        if (!p.mtd_guardar()) return;

        // Evitar duplicados en la tabla
        if (!Proveedor.existeRegistro(modeloProveedor, p.getCedula())) {
            modeloProveedor.addRow(new Object[]{
                p.getCedula(), p.getNombre(), p.getDireccion(),
                p.getTelefono(), p.getEmail(),
                new java.text.SimpleDateFormat("yyyy-MM-dd").format(p.getFechaRegistro()),
                p.getCodigoProvincia(), p.getCodigoPostal(), p.getSaldo()
            });
        }
        limpiarCampos();
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        if (!editMode) {
            JOptionPane.showMessageDialog(this, "Use BUSCAR primero.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (!validarCampos()) return;
        Proveedor p = new Proveedor(
            txt_cedula.getText().trim(),
            txt_nombre.getText().trim(),
            txt_direccion.getText().trim(),
            txt_telefono.getText().trim(),
            txt_email.getText().trim(),
            cb_fecharegistro.getDate(),
            txt_codigoprovincia.getText().trim(),
            txt_codigopostal.getText().trim(),
            Double.parseDouble(txt_saldo.getText().trim())
        );
        if (!p.mtd_guardar()) return;
        // actualizar tabla
        modeloProveedor.setValueAt(p.getNombre(),          editRow, 1);
        modeloProveedor.setValueAt(p.getDireccion(),       editRow, 2);
        modeloProveedor.setValueAt(p.getTelefono(),        editRow, 3);
        modeloProveedor.setValueAt(p.getEmail(),           editRow, 4);
        modeloProveedor.setValueAt(
            new java.text.SimpleDateFormat("yyyy-MM-dd").format(p.getFechaRegistro()),
            editRow, 5
        );
        modeloProveedor.setValueAt(p.getCodigoProvincia(), editRow, 6);
        modeloProveedor.setValueAt(p.getCodigoPostal(),    editRow, 7);
        modeloProveedor.setValueAt(p.getSaldo(),           editRow, 8);

        JOptionPane.showMessageDialog(this, "Proveedor actualizado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        editMode = false;
        editRow = -1;
        btn_editar.setText("EDITAR");
        limpiarCampos();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
       if (editMode) {
            JOptionPane.showMessageDialog(this, "Termine edición antes de eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int fila = tabla_proveedor.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione fila para eliminar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String ced = modeloProveedor.getValueAt(fila,0).toString();
        Proveedor p = new Proveedor();
        p.setCedula(ced);
        if (!p.mtd_eliminar()) return;
        modeloProveedor.removeRow(fila);
        limpiarCampos();
        JOptionPane.showMessageDialog(this, "Proveedor eliminado.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private boolean validarCampos() {
        String ced = txt_cedula.getText().trim();
        if (ced.isEmpty() || !Validacion.validarCedula(ced)) {
            JOptionPane.showMessageDialog(this, "Cédula inválida.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (txt_nombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese el nombre.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        String tel = txt_telefono.getText().trim();
        if (tel.isEmpty() || !Validacion.validarTelefono(tel)) {
            JOptionPane.showMessageDialog(this, "Teléfono inválido.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        String mail = txt_email.getText().trim();
        if (mail.isEmpty() || !Validacion.validarEmail(mail)) {
            JOptionPane.showMessageDialog(this, "Email inválido.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        if (cb_fecharegistro.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Seleccione la fecha de registro.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        try {
            Double.parseDouble(txt_saldo.getText().trim());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Saldo inválido.", "Error", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private org.jdesktop.swingx.JXDatePicker cb_fecharegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_proveedor;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_codigopostal;
    private javax.swing.JTextField txt_codigoprovincia;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_saldo;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
